// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: offline_ticket.proto

package steamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Offline_Ticket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EncryptedTicket []byte                 `protobuf:"bytes,1,opt,name=encrypted_ticket,json=encryptedTicket" json:"encrypted_ticket,omitempty"`
	Signature       []byte                 `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Kdf1            *int32                 `protobuf:"varint,3,opt,name=kdf1" json:"kdf1,omitempty"`
	Salt1           []byte                 `protobuf:"bytes,4,opt,name=salt1" json:"salt1,omitempty"`
	Kdf2            *int32                 `protobuf:"varint,5,opt,name=kdf2" json:"kdf2,omitempty"`
	Salt2           []byte                 `protobuf:"bytes,6,opt,name=salt2" json:"salt2,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Offline_Ticket) Reset() {
	*x = Offline_Ticket{}
	mi := &file_offline_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offline_Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offline_Ticket) ProtoMessage() {}

func (x *Offline_Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_offline_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offline_Ticket.ProtoReflect.Descriptor instead.
func (*Offline_Ticket) Descriptor() ([]byte, []int) {
	return file_offline_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *Offline_Ticket) GetEncryptedTicket() []byte {
	if x != nil {
		return x.EncryptedTicket
	}
	return nil
}

func (x *Offline_Ticket) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Offline_Ticket) GetKdf1() int32 {
	if x != nil && x.Kdf1 != nil {
		return *x.Kdf1
	}
	return 0
}

func (x *Offline_Ticket) GetSalt1() []byte {
	if x != nil {
		return x.Salt1
	}
	return nil
}

func (x *Offline_Ticket) GetKdf2() int32 {
	if x != nil && x.Kdf2 != nil {
		return *x.Kdf2
	}
	return 0
}

func (x *Offline_Ticket) GetSalt2() []byte {
	if x != nil {
		return x.Salt2
	}
	return nil
}

var File_offline_ticket_proto protoreflect.FileDescriptor

const file_offline_ticket_proto_rawDesc = "" +
	"\n" +
	"\x14offline_ticket.proto\"\xad\x01\n" +
	"\x0eOffline_Ticket\x12)\n" +
	"\x10encrypted_ticket\x18\x01 \x01(\fR\x0fencryptedTicket\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x12\n" +
	"\x04kdf1\x18\x03 \x01(\x05R\x04kdf1\x12\x14\n" +
	"\x05salt1\x18\x04 \x01(\fR\x05salt1\x12\x12\n" +
	"\x04kdf2\x18\x05 \x01(\x05R\x04kdf2\x12\x14\n" +
	"\x05salt2\x18\x06 \x01(\fR\x05salt2"

var (
	file_offline_ticket_proto_rawDescOnce sync.Once
	file_offline_ticket_proto_rawDescData []byte
)

func file_offline_ticket_proto_rawDescGZIP() []byte {
	file_offline_ticket_proto_rawDescOnce.Do(func() {
		file_offline_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offline_ticket_proto_rawDesc), len(file_offline_ticket_proto_rawDesc)))
	})
	return file_offline_ticket_proto_rawDescData
}

var file_offline_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_offline_ticket_proto_goTypes = []any{
	(*Offline_Ticket)(nil), // 0: Offline_Ticket
}
var file_offline_ticket_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_offline_ticket_proto_init() }
func file_offline_ticket_proto_init() {
	if File_offline_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offline_ticket_proto_rawDesc), len(file_offline_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offline_ticket_proto_goTypes,
		DependencyIndexes: file_offline_ticket_proto_depIdxs,
		MessageInfos:      file_offline_ticket_proto_msgTypes,
	}.Build()
	File_offline_ticket_proto = out.File
	file_offline_ticket_proto_goTypes = nil
	file_offline_ticket_proto_depIdxs = nil
}
