// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: steammessages_remoteclient_service.steamclient.proto

package steamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_steammessages_remoteclient_service_steamclient_proto protoreflect.FileDescriptor

const file_steammessages_remoteclient_service_steamclient_proto_rawDesc = "" +
	"\n" +
	"4steammessages_remoteclient_service.steamclient.proto\x1a\x18steammessages_base.proto\x1a,steammessages_unified_base.steamclient.proto\x1a1steammessages_remoteclient_service_messages.proto2\x85\v\n" +
	"\fRemoteClient\x12_\n" +
	"\x0eGetPairingInfo\x12%.CRemoteClient_GetPairingInfo_Request\x1a&.CRemoteClient_GetPairingInfo_Response\x12?\n" +
	"\fNotifyOnline\x12\".CRemoteClient_Online_Notification\x1a\v.NoResponse\x12e\n" +
	"\x10GetRecentClients\x12'.CRemoteClient_GetRecentClients_Request\x1a(.CRemoteClient_GetRecentClients_Response\x12e\n" +
	"\x10MarkTaskComplete\x12'.CRemoteClient_MarkTaskComplete_Request\x1a(.CRemoteClient_MarkTaskComplete_Response\x12I\n" +
	"\x11NotifyReplyPacket\x12'.CRemoteClient_ReplyPacket_Notification\x1a\v.NoResponse\x12n\n" +
	"\x13AllocateRelayServer\x12*.CRemoteClient_AllocateRelayServer_Request\x1a+.CRemoteClient_AllocateRelayServer_Response\x12V\n" +
	"\vAllocateSDR\x12\".CRemoteClient_AllocateSDR_Request\x1a#.CRemoteClient_AllocateSDR_Response\x12S\n" +
	"\x18SendSteamBroadcastPacket\x12*.CRemoteClient_SteamBroadcast_Notification\x1a\v.NoResponse\x12O\n" +
	"\x16SendSteamToSteamPacket\x12(.CRemoteClient_SteamToSteam_Notification\x1a\v.NoResponse\x12i\n" +
	"\x1cSendRemotePlaySessionStarted\x12#.CRemotePlay_SessionStarted_Request\x1a$.CRemotePlay_SessionStarted_Response\x12U\n" +
	"\x1cSendRemotePlaySessionStopped\x12(.CRemotePlay_SessionStopped_Notification\x1a\v.NoResponse\x12N\n" +
	"\x1cSendRemotePlayTogetherPacket\x12!.CRemotePlayTogether_Notification\x1a\v.NoResponse\x12\x9b\x01\n" +
	"\"CreateRemotePlayTogetherInvitation\x129.CRemoteClient_CreateRemotePlayTogetherInvitation_Request\x1a:.CRemoteClient_CreateRemotePlayTogetherInvitation_Response\x12\x9b\x01\n" +
	"\"DeleteRemotePlayTogetherInvitation\x129.CRemoteClient_DeleteRemotePlayTogetherInvitation_Request\x1a:.CRemoteClient_DeleteRemotePlayTogetherInvitation_Response2\xa7\x06\n" +
	"\x17RemoteClientSteamClient\x12[\n" +
	"\x1aNotifyRegisterStatusUpdate\x120.CRemoteClient_RegisterStatusUpdate_Notification\x1a\v.NoResponse\x12_\n" +
	"\x1cNotifyUnregisterStatusUpdate\x122.CRemoteClient_UnregisterStatusUpdate_Notification\x1a\v.NoResponse\x12K\n" +
	"\x12NotifyRemotePacket\x12(.CRemoteClient_RemotePacket_Notification\x1a\v.NoResponse\x12[\n" +
	"\x1aNotifyEnableSteamBroadcast\x120.CRemoteClient_EnableSteamBroadcast_Notification\x1a\v.NoResponse\x12]\n" +
	"\x1bNotifyDisableSteamBroadcast\x121.CRemoteClient_DisableSteamBroadcast_Notification\x1a\v.NoResponse\x12U\n" +
	"\x1aNotifySteamBroadcastPacket\x12*.CRemoteClient_SteamBroadcast_Notification\x1a\v.NoResponse\x12Q\n" +
	"\x18NotifySteamToSteamPacket\x12(.CRemoteClient_SteamToSteam_Notification\x1a\v.NoResponse\x12P\n" +
	"\x1eNotifyRemotePlayTogetherPacket\x12!.CRemotePlayTogether_Notification\x1a\v.NoResponse\x12C\n" +
	"\x0eNotifyTaskList\x12$.CRemoteClient_TaskList_Notification\x1a\v.NoResponse\x1a\x04\xc0\xb5\x18\x02B\x03\x80\x01\x01"

var file_steammessages_remoteclient_service_steamclient_proto_goTypes = []any{
	(*CRemoteClient_GetPairingInfo_Request)(nil),                     // 0: CRemoteClient_GetPairingInfo_Request
	(*CRemoteClient_Online_Notification)(nil),                        // 1: CRemoteClient_Online_Notification
	(*CRemoteClient_GetRecentClients_Request)(nil),                   // 2: CRemoteClient_GetRecentClients_Request
	(*CRemoteClient_MarkTaskComplete_Request)(nil),                   // 3: CRemoteClient_MarkTaskComplete_Request
	(*CRemoteClient_ReplyPacket_Notification)(nil),                   // 4: CRemoteClient_ReplyPacket_Notification
	(*CRemoteClient_AllocateRelayServer_Request)(nil),                // 5: CRemoteClient_AllocateRelayServer_Request
	(*CRemoteClient_AllocateSDR_Request)(nil),                        // 6: CRemoteClient_AllocateSDR_Request
	(*CRemoteClient_SteamBroadcast_Notification)(nil),                // 7: CRemoteClient_SteamBroadcast_Notification
	(*CRemoteClient_SteamToSteam_Notification)(nil),                  // 8: CRemoteClient_SteamToSteam_Notification
	(*CRemotePlay_SessionStarted_Request)(nil),                       // 9: CRemotePlay_SessionStarted_Request
	(*CRemotePlay_SessionStopped_Notification)(nil),                  // 10: CRemotePlay_SessionStopped_Notification
	(*CRemotePlayTogether_Notification)(nil),                         // 11: CRemotePlayTogether_Notification
	(*CRemoteClient_CreateRemotePlayTogetherInvitation_Request)(nil), // 12: CRemoteClient_CreateRemotePlayTogetherInvitation_Request
	(*CRemoteClient_DeleteRemotePlayTogetherInvitation_Request)(nil), // 13: CRemoteClient_DeleteRemotePlayTogetherInvitation_Request
	(*CRemoteClient_RegisterStatusUpdate_Notification)(nil),          // 14: CRemoteClient_RegisterStatusUpdate_Notification
	(*CRemoteClient_UnregisterStatusUpdate_Notification)(nil),        // 15: CRemoteClient_UnregisterStatusUpdate_Notification
	(*CRemoteClient_RemotePacket_Notification)(nil),                  // 16: CRemoteClient_RemotePacket_Notification
	(*CRemoteClient_EnableSteamBroadcast_Notification)(nil),          // 17: CRemoteClient_EnableSteamBroadcast_Notification
	(*CRemoteClient_DisableSteamBroadcast_Notification)(nil),         // 18: CRemoteClient_DisableSteamBroadcast_Notification
	(*CRemoteClient_TaskList_Notification)(nil),                      // 19: CRemoteClient_TaskList_Notification
	(*CRemoteClient_GetPairingInfo_Response)(nil),                    // 20: CRemoteClient_GetPairingInfo_Response
	(*NoResponse)(nil), // 21: NoResponse
	(*CRemoteClient_GetRecentClients_Response)(nil),                   // 22: CRemoteClient_GetRecentClients_Response
	(*CRemoteClient_MarkTaskComplete_Response)(nil),                   // 23: CRemoteClient_MarkTaskComplete_Response
	(*CRemoteClient_AllocateRelayServer_Response)(nil),                // 24: CRemoteClient_AllocateRelayServer_Response
	(*CRemoteClient_AllocateSDR_Response)(nil),                        // 25: CRemoteClient_AllocateSDR_Response
	(*CRemotePlay_SessionStarted_Response)(nil),                       // 26: CRemotePlay_SessionStarted_Response
	(*CRemoteClient_CreateRemotePlayTogetherInvitation_Response)(nil), // 27: CRemoteClient_CreateRemotePlayTogetherInvitation_Response
	(*CRemoteClient_DeleteRemotePlayTogetherInvitation_Response)(nil), // 28: CRemoteClient_DeleteRemotePlayTogetherInvitation_Response
}
var file_steammessages_remoteclient_service_steamclient_proto_depIdxs = []int32{
	0,  // 0: RemoteClient.GetPairingInfo:input_type -> CRemoteClient_GetPairingInfo_Request
	1,  // 1: RemoteClient.NotifyOnline:input_type -> CRemoteClient_Online_Notification
	2,  // 2: RemoteClient.GetRecentClients:input_type -> CRemoteClient_GetRecentClients_Request
	3,  // 3: RemoteClient.MarkTaskComplete:input_type -> CRemoteClient_MarkTaskComplete_Request
	4,  // 4: RemoteClient.NotifyReplyPacket:input_type -> CRemoteClient_ReplyPacket_Notification
	5,  // 5: RemoteClient.AllocateRelayServer:input_type -> CRemoteClient_AllocateRelayServer_Request
	6,  // 6: RemoteClient.AllocateSDR:input_type -> CRemoteClient_AllocateSDR_Request
	7,  // 7: RemoteClient.SendSteamBroadcastPacket:input_type -> CRemoteClient_SteamBroadcast_Notification
	8,  // 8: RemoteClient.SendSteamToSteamPacket:input_type -> CRemoteClient_SteamToSteam_Notification
	9,  // 9: RemoteClient.SendRemotePlaySessionStarted:input_type -> CRemotePlay_SessionStarted_Request
	10, // 10: RemoteClient.SendRemotePlaySessionStopped:input_type -> CRemotePlay_SessionStopped_Notification
	11, // 11: RemoteClient.SendRemotePlayTogetherPacket:input_type -> CRemotePlayTogether_Notification
	12, // 12: RemoteClient.CreateRemotePlayTogetherInvitation:input_type -> CRemoteClient_CreateRemotePlayTogetherInvitation_Request
	13, // 13: RemoteClient.DeleteRemotePlayTogetherInvitation:input_type -> CRemoteClient_DeleteRemotePlayTogetherInvitation_Request
	14, // 14: RemoteClientSteamClient.NotifyRegisterStatusUpdate:input_type -> CRemoteClient_RegisterStatusUpdate_Notification
	15, // 15: RemoteClientSteamClient.NotifyUnregisterStatusUpdate:input_type -> CRemoteClient_UnregisterStatusUpdate_Notification
	16, // 16: RemoteClientSteamClient.NotifyRemotePacket:input_type -> CRemoteClient_RemotePacket_Notification
	17, // 17: RemoteClientSteamClient.NotifyEnableSteamBroadcast:input_type -> CRemoteClient_EnableSteamBroadcast_Notification
	18, // 18: RemoteClientSteamClient.NotifyDisableSteamBroadcast:input_type -> CRemoteClient_DisableSteamBroadcast_Notification
	7,  // 19: RemoteClientSteamClient.NotifySteamBroadcastPacket:input_type -> CRemoteClient_SteamBroadcast_Notification
	8,  // 20: RemoteClientSteamClient.NotifySteamToSteamPacket:input_type -> CRemoteClient_SteamToSteam_Notification
	11, // 21: RemoteClientSteamClient.NotifyRemotePlayTogetherPacket:input_type -> CRemotePlayTogether_Notification
	19, // 22: RemoteClientSteamClient.NotifyTaskList:input_type -> CRemoteClient_TaskList_Notification
	20, // 23: RemoteClient.GetPairingInfo:output_type -> CRemoteClient_GetPairingInfo_Response
	21, // 24: RemoteClient.NotifyOnline:output_type -> NoResponse
	22, // 25: RemoteClient.GetRecentClients:output_type -> CRemoteClient_GetRecentClients_Response
	23, // 26: RemoteClient.MarkTaskComplete:output_type -> CRemoteClient_MarkTaskComplete_Response
	21, // 27: RemoteClient.NotifyReplyPacket:output_type -> NoResponse
	24, // 28: RemoteClient.AllocateRelayServer:output_type -> CRemoteClient_AllocateRelayServer_Response
	25, // 29: RemoteClient.AllocateSDR:output_type -> CRemoteClient_AllocateSDR_Response
	21, // 30: RemoteClient.SendSteamBroadcastPacket:output_type -> NoResponse
	21, // 31: RemoteClient.SendSteamToSteamPacket:output_type -> NoResponse
	26, // 32: RemoteClient.SendRemotePlaySessionStarted:output_type -> CRemotePlay_SessionStarted_Response
	21, // 33: RemoteClient.SendRemotePlaySessionStopped:output_type -> NoResponse
	21, // 34: RemoteClient.SendRemotePlayTogetherPacket:output_type -> NoResponse
	27, // 35: RemoteClient.CreateRemotePlayTogetherInvitation:output_type -> CRemoteClient_CreateRemotePlayTogetherInvitation_Response
	28, // 36: RemoteClient.DeleteRemotePlayTogetherInvitation:output_type -> CRemoteClient_DeleteRemotePlayTogetherInvitation_Response
	21, // 37: RemoteClientSteamClient.NotifyRegisterStatusUpdate:output_type -> NoResponse
	21, // 38: RemoteClientSteamClient.NotifyUnregisterStatusUpdate:output_type -> NoResponse
	21, // 39: RemoteClientSteamClient.NotifyRemotePacket:output_type -> NoResponse
	21, // 40: RemoteClientSteamClient.NotifyEnableSteamBroadcast:output_type -> NoResponse
	21, // 41: RemoteClientSteamClient.NotifyDisableSteamBroadcast:output_type -> NoResponse
	21, // 42: RemoteClientSteamClient.NotifySteamBroadcastPacket:output_type -> NoResponse
	21, // 43: RemoteClientSteamClient.NotifySteamToSteamPacket:output_type -> NoResponse
	21, // 44: RemoteClientSteamClient.NotifyRemotePlayTogetherPacket:output_type -> NoResponse
	21, // 45: RemoteClientSteamClient.NotifyTaskList:output_type -> NoResponse
	23, // [23:46] is the sub-list for method output_type
	0,  // [0:23] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_steammessages_remoteclient_service_steamclient_proto_init() }
func file_steammessages_remoteclient_service_steamclient_proto_init() {
	if File_steammessages_remoteclient_service_steamclient_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	file_steammessages_unified_base_steamclient_proto_init()
	file_steammessages_remoteclient_service_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_remoteclient_service_steamclient_proto_rawDesc), len(file_steammessages_remoteclient_service_steamclient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_steammessages_remoteclient_service_steamclient_proto_goTypes,
		DependencyIndexes: file_steammessages_remoteclient_service_steamclient_proto_depIdxs,
	}.Build()
	File_steammessages_remoteclient_service_steamclient_proto = out.File
	file_steammessages_remoteclient_service_steamclient_proto_goTypes = nil
	file_steammessages_remoteclient_service_steamclient_proto_depIdxs = nil
}
