// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: steammessages_clientserver_lbs.proto

package steamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgClientLBSSetScore struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AppId             *uint32                `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	LeaderboardId     *int32                 `protobuf:"varint,2,opt,name=leaderboard_id,json=leaderboardId" json:"leaderboard_id,omitempty"`
	Score             *int32                 `protobuf:"varint,3,opt,name=score" json:"score,omitempty"`
	Details           []byte                 `protobuf:"bytes,4,opt,name=details" json:"details,omitempty"`
	UploadScoreMethod *int32                 `protobuf:"varint,5,opt,name=upload_score_method,json=uploadScoreMethod" json:"upload_score_method,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CMsgClientLBSSetScore) Reset() {
	*x = CMsgClientLBSSetScore{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSSetScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSSetScore) ProtoMessage() {}

func (x *CMsgClientLBSSetScore) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSSetScore.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSSetScore) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgClientLBSSetScore) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientLBSSetScore) GetLeaderboardId() int32 {
	if x != nil && x.LeaderboardId != nil {
		return *x.LeaderboardId
	}
	return 0
}

func (x *CMsgClientLBSSetScore) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *CMsgClientLBSSetScore) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CMsgClientLBSSetScore) GetUploadScoreMethod() int32 {
	if x != nil && x.UploadScoreMethod != nil {
		return *x.UploadScoreMethod
	}
	return 0
}

type CMsgClientLBSSetScoreResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Eresult               *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	LeaderboardEntryCount *int32                 `protobuf:"varint,2,opt,name=leaderboard_entry_count,json=leaderboardEntryCount" json:"leaderboard_entry_count,omitempty"`
	ScoreChanged          *bool                  `protobuf:"varint,3,opt,name=score_changed,json=scoreChanged" json:"score_changed,omitempty"`
	GlobalRankPrevious    *int32                 `protobuf:"varint,4,opt,name=global_rank_previous,json=globalRankPrevious" json:"global_rank_previous,omitempty"`
	GlobalRankNew         *int32                 `protobuf:"varint,5,opt,name=global_rank_new,json=globalRankNew" json:"global_rank_new,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

// Default values for CMsgClientLBSSetScoreResponse fields.
const (
	Default_CMsgClientLBSSetScoreResponse_Eresult = int32(2)
)

func (x *CMsgClientLBSSetScoreResponse) Reset() {
	*x = CMsgClientLBSSetScoreResponse{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSSetScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSSetScoreResponse) ProtoMessage() {}

func (x *CMsgClientLBSSetScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSSetScoreResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSSetScoreResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgClientLBSSetScoreResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientLBSSetScoreResponse_Eresult
}

func (x *CMsgClientLBSSetScoreResponse) GetLeaderboardEntryCount() int32 {
	if x != nil && x.LeaderboardEntryCount != nil {
		return *x.LeaderboardEntryCount
	}
	return 0
}

func (x *CMsgClientLBSSetScoreResponse) GetScoreChanged() bool {
	if x != nil && x.ScoreChanged != nil {
		return *x.ScoreChanged
	}
	return false
}

func (x *CMsgClientLBSSetScoreResponse) GetGlobalRankPrevious() int32 {
	if x != nil && x.GlobalRankPrevious != nil {
		return *x.GlobalRankPrevious
	}
	return 0
}

func (x *CMsgClientLBSSetScoreResponse) GetGlobalRankNew() int32 {
	if x != nil && x.GlobalRankNew != nil {
		return *x.GlobalRankNew
	}
	return 0
}

type CMsgClientLBSSetUGC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         *uint32                `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	LeaderboardId *int32                 `protobuf:"varint,2,opt,name=leaderboard_id,json=leaderboardId" json:"leaderboard_id,omitempty"`
	UgcId         *uint64                `protobuf:"fixed64,3,opt,name=ugc_id,json=ugcId" json:"ugc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientLBSSetUGC) Reset() {
	*x = CMsgClientLBSSetUGC{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSSetUGC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSSetUGC) ProtoMessage() {}

func (x *CMsgClientLBSSetUGC) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSSetUGC.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSSetUGC) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgClientLBSSetUGC) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientLBSSetUGC) GetLeaderboardId() int32 {
	if x != nil && x.LeaderboardId != nil {
		return *x.LeaderboardId
	}
	return 0
}

func (x *CMsgClientLBSSetUGC) GetUgcId() uint64 {
	if x != nil && x.UgcId != nil {
		return *x.UgcId
	}
	return 0
}

type CMsgClientLBSSetUGCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eresult       *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientLBSSetUGCResponse fields.
const (
	Default_CMsgClientLBSSetUGCResponse_Eresult = int32(2)
)

func (x *CMsgClientLBSSetUGCResponse) Reset() {
	*x = CMsgClientLBSSetUGCResponse{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSSetUGCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSSetUGCResponse) ProtoMessage() {}

func (x *CMsgClientLBSSetUGCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSSetUGCResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSSetUGCResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgClientLBSSetUGCResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientLBSSetUGCResponse_Eresult
}

type CMsgClientLBSFindOrCreateLB struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AppId                  *uint32                `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	LeaderboardSortMethod  *int32                 `protobuf:"varint,2,opt,name=leaderboard_sort_method,json=leaderboardSortMethod" json:"leaderboard_sort_method,omitempty"`
	LeaderboardDisplayType *int32                 `protobuf:"varint,3,opt,name=leaderboard_display_type,json=leaderboardDisplayType" json:"leaderboard_display_type,omitempty"`
	CreateIfNotFound       *bool                  `protobuf:"varint,4,opt,name=create_if_not_found,json=createIfNotFound" json:"create_if_not_found,omitempty"`
	LeaderboardName        *string                `protobuf:"bytes,5,opt,name=leaderboard_name,json=leaderboardName" json:"leaderboard_name,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CMsgClientLBSFindOrCreateLB) Reset() {
	*x = CMsgClientLBSFindOrCreateLB{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSFindOrCreateLB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSFindOrCreateLB) ProtoMessage() {}

func (x *CMsgClientLBSFindOrCreateLB) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSFindOrCreateLB.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSFindOrCreateLB) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{4}
}

func (x *CMsgClientLBSFindOrCreateLB) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientLBSFindOrCreateLB) GetLeaderboardSortMethod() int32 {
	if x != nil && x.LeaderboardSortMethod != nil {
		return *x.LeaderboardSortMethod
	}
	return 0
}

func (x *CMsgClientLBSFindOrCreateLB) GetLeaderboardDisplayType() int32 {
	if x != nil && x.LeaderboardDisplayType != nil {
		return *x.LeaderboardDisplayType
	}
	return 0
}

func (x *CMsgClientLBSFindOrCreateLB) GetCreateIfNotFound() bool {
	if x != nil && x.CreateIfNotFound != nil {
		return *x.CreateIfNotFound
	}
	return false
}

func (x *CMsgClientLBSFindOrCreateLB) GetLeaderboardName() string {
	if x != nil && x.LeaderboardName != nil {
		return *x.LeaderboardName
	}
	return ""
}

type CMsgClientLBSFindOrCreateLBResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Eresult                *int32                 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	LeaderboardId          *int32                 `protobuf:"varint,2,opt,name=leaderboard_id,json=leaderboardId" json:"leaderboard_id,omitempty"`
	LeaderboardEntryCount  *int32                 `protobuf:"varint,3,opt,name=leaderboard_entry_count,json=leaderboardEntryCount" json:"leaderboard_entry_count,omitempty"`
	LeaderboardSortMethod  *int32                 `protobuf:"varint,4,opt,name=leaderboard_sort_method,json=leaderboardSortMethod,def=0" json:"leaderboard_sort_method,omitempty"`
	LeaderboardDisplayType *int32                 `protobuf:"varint,5,opt,name=leaderboard_display_type,json=leaderboardDisplayType,def=0" json:"leaderboard_display_type,omitempty"`
	LeaderboardName        *string                `protobuf:"bytes,6,opt,name=leaderboard_name,json=leaderboardName" json:"leaderboard_name,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

// Default values for CMsgClientLBSFindOrCreateLBResponse fields.
const (
	Default_CMsgClientLBSFindOrCreateLBResponse_Eresult                = int32(2)
	Default_CMsgClientLBSFindOrCreateLBResponse_LeaderboardSortMethod  = int32(0)
	Default_CMsgClientLBSFindOrCreateLBResponse_LeaderboardDisplayType = int32(0)
)

func (x *CMsgClientLBSFindOrCreateLBResponse) Reset() {
	*x = CMsgClientLBSFindOrCreateLBResponse{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSFindOrCreateLBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSFindOrCreateLBResponse) ProtoMessage() {}

func (x *CMsgClientLBSFindOrCreateLBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSFindOrCreateLBResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSFindOrCreateLBResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{5}
}

func (x *CMsgClientLBSFindOrCreateLBResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientLBSFindOrCreateLBResponse_Eresult
}

func (x *CMsgClientLBSFindOrCreateLBResponse) GetLeaderboardId() int32 {
	if x != nil && x.LeaderboardId != nil {
		return *x.LeaderboardId
	}
	return 0
}

func (x *CMsgClientLBSFindOrCreateLBResponse) GetLeaderboardEntryCount() int32 {
	if x != nil && x.LeaderboardEntryCount != nil {
		return *x.LeaderboardEntryCount
	}
	return 0
}

func (x *CMsgClientLBSFindOrCreateLBResponse) GetLeaderboardSortMethod() int32 {
	if x != nil && x.LeaderboardSortMethod != nil {
		return *x.LeaderboardSortMethod
	}
	return Default_CMsgClientLBSFindOrCreateLBResponse_LeaderboardSortMethod
}

func (x *CMsgClientLBSFindOrCreateLBResponse) GetLeaderboardDisplayType() int32 {
	if x != nil && x.LeaderboardDisplayType != nil {
		return *x.LeaderboardDisplayType
	}
	return Default_CMsgClientLBSFindOrCreateLBResponse_LeaderboardDisplayType
}

func (x *CMsgClientLBSFindOrCreateLBResponse) GetLeaderboardName() string {
	if x != nil && x.LeaderboardName != nil {
		return *x.LeaderboardName
	}
	return ""
}

type CMsgClientLBSGetLBEntries struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AppId                  *int32                 `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	LeaderboardId          *int32                 `protobuf:"varint,2,opt,name=leaderboard_id,json=leaderboardId" json:"leaderboard_id,omitempty"`
	RangeStart             *int32                 `protobuf:"varint,3,opt,name=range_start,json=rangeStart" json:"range_start,omitempty"`
	RangeEnd               *int32                 `protobuf:"varint,4,opt,name=range_end,json=rangeEnd" json:"range_end,omitempty"`
	LeaderboardDataRequest *int32                 `protobuf:"varint,5,opt,name=leaderboard_data_request,json=leaderboardDataRequest" json:"leaderboard_data_request,omitempty"`
	Steamids               []uint64               `protobuf:"fixed64,6,rep,name=steamids" json:"steamids,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CMsgClientLBSGetLBEntries) Reset() {
	*x = CMsgClientLBSGetLBEntries{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSGetLBEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSGetLBEntries) ProtoMessage() {}

func (x *CMsgClientLBSGetLBEntries) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSGetLBEntries.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSGetLBEntries) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{6}
}

func (x *CMsgClientLBSGetLBEntries) GetAppId() int32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntries) GetLeaderboardId() int32 {
	if x != nil && x.LeaderboardId != nil {
		return *x.LeaderboardId
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntries) GetRangeStart() int32 {
	if x != nil && x.RangeStart != nil {
		return *x.RangeStart
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntries) GetRangeEnd() int32 {
	if x != nil && x.RangeEnd != nil {
		return *x.RangeEnd
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntries) GetLeaderboardDataRequest() int32 {
	if x != nil && x.LeaderboardDataRequest != nil {
		return *x.LeaderboardDataRequest
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntries) GetSteamids() []uint64 {
	if x != nil {
		return x.Steamids
	}
	return nil
}

type CMsgClientLBSGetLBEntriesResponse struct {
	state                 protoimpl.MessageState                     `protogen:"open.v1"`
	Eresult               *int32                                     `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	LeaderboardEntryCount *int32                                     `protobuf:"varint,2,opt,name=leaderboard_entry_count,json=leaderboardEntryCount" json:"leaderboard_entry_count,omitempty"`
	Entries               []*CMsgClientLBSGetLBEntriesResponse_Entry `protobuf:"bytes,3,rep,name=entries" json:"entries,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

// Default values for CMsgClientLBSGetLBEntriesResponse fields.
const (
	Default_CMsgClientLBSGetLBEntriesResponse_Eresult = int32(2)
)

func (x *CMsgClientLBSGetLBEntriesResponse) Reset() {
	*x = CMsgClientLBSGetLBEntriesResponse{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSGetLBEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSGetLBEntriesResponse) ProtoMessage() {}

func (x *CMsgClientLBSGetLBEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSGetLBEntriesResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSGetLBEntriesResponse) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{7}
}

func (x *CMsgClientLBSGetLBEntriesResponse) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgClientLBSGetLBEntriesResponse_Eresult
}

func (x *CMsgClientLBSGetLBEntriesResponse) GetLeaderboardEntryCount() int32 {
	if x != nil && x.LeaderboardEntryCount != nil {
		return *x.LeaderboardEntryCount
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntriesResponse) GetEntries() []*CMsgClientLBSGetLBEntriesResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CMsgClientLBSGetLBEntriesResponse_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamIdUser   *uint64                `protobuf:"fixed64,1,opt,name=steam_id_user,json=steamIdUser" json:"steam_id_user,omitempty"`
	GlobalRank    *int32                 `protobuf:"varint,2,opt,name=global_rank,json=globalRank" json:"global_rank,omitempty"`
	Score         *int32                 `protobuf:"varint,3,opt,name=score" json:"score,omitempty"`
	Details       []byte                 `protobuf:"bytes,4,opt,name=details" json:"details,omitempty"`
	UgcId         *uint64                `protobuf:"fixed64,5,opt,name=ugc_id,json=ugcId" json:"ugc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientLBSGetLBEntriesResponse_Entry) Reset() {
	*x = CMsgClientLBSGetLBEntriesResponse_Entry{}
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientLBSGetLBEntriesResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientLBSGetLBEntriesResponse_Entry) ProtoMessage() {}

func (x *CMsgClientLBSGetLBEntriesResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_clientserver_lbs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientLBSGetLBEntriesResponse_Entry.ProtoReflect.Descriptor instead.
func (*CMsgClientLBSGetLBEntriesResponse_Entry) Descriptor() ([]byte, []int) {
	return file_steammessages_clientserver_lbs_proto_rawDescGZIP(), []int{7, 0}
}

func (x *CMsgClientLBSGetLBEntriesResponse_Entry) GetSteamIdUser() uint64 {
	if x != nil && x.SteamIdUser != nil {
		return *x.SteamIdUser
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntriesResponse_Entry) GetGlobalRank() int32 {
	if x != nil && x.GlobalRank != nil {
		return *x.GlobalRank
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntriesResponse_Entry) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *CMsgClientLBSGetLBEntriesResponse_Entry) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CMsgClientLBSGetLBEntriesResponse_Entry) GetUgcId() uint64 {
	if x != nil && x.UgcId != nil {
		return *x.UgcId
	}
	return 0
}

var File_steammessages_clientserver_lbs_proto protoreflect.FileDescriptor

const file_steammessages_clientserver_lbs_proto_rawDesc = "" +
	"\n" +
	"$steammessages_clientserver_lbs.proto\x1a\x18steammessages_base.proto\"\xb5\x01\n" +
	"\x15CMsgClientLBSSetScore\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12%\n" +
	"\x0eleaderboard_id\x18\x02 \x01(\x05R\rleaderboardId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\adetails\x18\x04 \x01(\fR\adetails\x12.\n" +
	"\x13upload_score_method\x18\x05 \x01(\x05R\x11uploadScoreMethod\"\xf3\x01\n" +
	"\x1dCMsgClientLBSSetScoreResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x126\n" +
	"\x17leaderboard_entry_count\x18\x02 \x01(\x05R\x15leaderboardEntryCount\x12#\n" +
	"\rscore_changed\x18\x03 \x01(\bR\fscoreChanged\x120\n" +
	"\x14global_rank_previous\x18\x04 \x01(\x05R\x12globalRankPrevious\x12&\n" +
	"\x0fglobal_rank_new\x18\x05 \x01(\x05R\rglobalRankNew\"j\n" +
	"\x13CMsgClientLBSSetUGC\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12%\n" +
	"\x0eleaderboard_id\x18\x02 \x01(\x05R\rleaderboardId\x12\x15\n" +
	"\x06ugc_id\x18\x03 \x01(\x06R\x05ugcId\":\n" +
	"\x1bCMsgClientLBSSetUGCResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\"\x80\x02\n" +
	"\x1bCMsgClientLBSFindOrCreateLB\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x126\n" +
	"\x17leaderboard_sort_method\x18\x02 \x01(\x05R\x15leaderboardSortMethod\x128\n" +
	"\x18leaderboard_display_type\x18\x03 \x01(\x05R\x16leaderboardDisplayType\x12-\n" +
	"\x13create_if_not_found\x18\x04 \x01(\bR\x10createIfNotFound\x12)\n" +
	"\x10leaderboard_name\x18\x05 \x01(\tR\x0fleaderboardName\"\xc4\x02\n" +
	"#CMsgClientLBSFindOrCreateLBResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x12%\n" +
	"\x0eleaderboard_id\x18\x02 \x01(\x05R\rleaderboardId\x126\n" +
	"\x17leaderboard_entry_count\x18\x03 \x01(\x05R\x15leaderboardEntryCount\x129\n" +
	"\x17leaderboard_sort_method\x18\x04 \x01(\x05:\x010R\x15leaderboardSortMethod\x12;\n" +
	"\x18leaderboard_display_type\x18\x05 \x01(\x05:\x010R\x16leaderboardDisplayType\x12)\n" +
	"\x10leaderboard_name\x18\x06 \x01(\tR\x0fleaderboardName\"\xed\x01\n" +
	"\x19CMsgClientLBSGetLBEntries\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x05R\x05appId\x12%\n" +
	"\x0eleaderboard_id\x18\x02 \x01(\x05R\rleaderboardId\x12\x1f\n" +
	"\vrange_start\x18\x03 \x01(\x05R\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x04 \x01(\x05R\brangeEnd\x128\n" +
	"\x18leaderboard_data_request\x18\x05 \x01(\x05R\x16leaderboardDataRequest\x12\x1a\n" +
	"\bsteamids\x18\x06 \x03(\x06R\bsteamids\"\xd2\x02\n" +
	"!CMsgClientLBSGetLBEntriesResponse\x12\x1b\n" +
	"\aeresult\x18\x01 \x01(\x05:\x012R\aeresult\x126\n" +
	"\x17leaderboard_entry_count\x18\x02 \x01(\x05R\x15leaderboardEntryCount\x12B\n" +
	"\aentries\x18\x03 \x03(\v2(.CMsgClientLBSGetLBEntriesResponse.EntryR\aentries\x1a\x93\x01\n" +
	"\x05Entry\x12\"\n" +
	"\rsteam_id_user\x18\x01 \x01(\x06R\vsteamIdUser\x12\x1f\n" +
	"\vglobal_rank\x18\x02 \x01(\x05R\n" +
	"globalRank\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\adetails\x18\x04 \x01(\fR\adetails\x12\x15\n" +
	"\x06ugc_id\x18\x05 \x01(\x06R\x05ugcIdB\x05H\x01\x80\x01\x00"

var (
	file_steammessages_clientserver_lbs_proto_rawDescOnce sync.Once
	file_steammessages_clientserver_lbs_proto_rawDescData []byte
)

func file_steammessages_clientserver_lbs_proto_rawDescGZIP() []byte {
	file_steammessages_clientserver_lbs_proto_rawDescOnce.Do(func() {
		file_steammessages_clientserver_lbs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_lbs_proto_rawDesc), len(file_steammessages_clientserver_lbs_proto_rawDesc)))
	})
	return file_steammessages_clientserver_lbs_proto_rawDescData
}

var file_steammessages_clientserver_lbs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_steammessages_clientserver_lbs_proto_goTypes = []any{
	(*CMsgClientLBSSetScore)(nil),                   // 0: CMsgClientLBSSetScore
	(*CMsgClientLBSSetScoreResponse)(nil),           // 1: CMsgClientLBSSetScoreResponse
	(*CMsgClientLBSSetUGC)(nil),                     // 2: CMsgClientLBSSetUGC
	(*CMsgClientLBSSetUGCResponse)(nil),             // 3: CMsgClientLBSSetUGCResponse
	(*CMsgClientLBSFindOrCreateLB)(nil),             // 4: CMsgClientLBSFindOrCreateLB
	(*CMsgClientLBSFindOrCreateLBResponse)(nil),     // 5: CMsgClientLBSFindOrCreateLBResponse
	(*CMsgClientLBSGetLBEntries)(nil),               // 6: CMsgClientLBSGetLBEntries
	(*CMsgClientLBSGetLBEntriesResponse)(nil),       // 7: CMsgClientLBSGetLBEntriesResponse
	(*CMsgClientLBSGetLBEntriesResponse_Entry)(nil), // 8: CMsgClientLBSGetLBEntriesResponse.Entry
}
var file_steammessages_clientserver_lbs_proto_depIdxs = []int32{
	8, // 0: CMsgClientLBSGetLBEntriesResponse.entries:type_name -> CMsgClientLBSGetLBEntriesResponse.Entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_steammessages_clientserver_lbs_proto_init() }
func file_steammessages_clientserver_lbs_proto_init() {
	if File_steammessages_clientserver_lbs_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_clientserver_lbs_proto_rawDesc), len(file_steammessages_clientserver_lbs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steammessages_clientserver_lbs_proto_goTypes,
		DependencyIndexes: file_steammessages_clientserver_lbs_proto_depIdxs,
		MessageInfos:      file_steammessages_clientserver_lbs_proto_msgTypes,
	}.Build()
	File_steammessages_clientserver_lbs_proto = out.File
	file_steammessages_clientserver_lbs_proto_goTypes = nil
	file_steammessages_clientserver_lbs_proto_depIdxs = nil
}
