// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: steammessages_econ.steamclient.proto

package steamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAssetPropertyType int32

const (
	EAssetPropertyType_k_EAssetPropertyType_Unknown EAssetPropertyType = 0
	EAssetPropertyType_k_EAssetPropertyType_Float   EAssetPropertyType = 1
	EAssetPropertyType_k_EAssetPropertyType_Int     EAssetPropertyType = 2
	EAssetPropertyType_k_EAssetPropertyType_String  EAssetPropertyType = 3
	EAssetPropertyType_k_EAssetPropertyType_MAX     EAssetPropertyType = 4
)

// Enum value maps for EAssetPropertyType.
var (
	EAssetPropertyType_name = map[int32]string{
		0: "k_EAssetPropertyType_Unknown",
		1: "k_EAssetPropertyType_Float",
		2: "k_EAssetPropertyType_Int",
		3: "k_EAssetPropertyType_String",
		4: "k_EAssetPropertyType_MAX",
	}
	EAssetPropertyType_value = map[string]int32{
		"k_EAssetPropertyType_Unknown": 0,
		"k_EAssetPropertyType_Float":   1,
		"k_EAssetPropertyType_Int":     2,
		"k_EAssetPropertyType_String":  3,
		"k_EAssetPropertyType_MAX":     4,
	}
)

func (x EAssetPropertyType) Enum() *EAssetPropertyType {
	p := new(EAssetPropertyType)
	*p = x
	return p
}

func (x EAssetPropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAssetPropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_steammessages_econ_steamclient_proto_enumTypes[0].Descriptor()
}

func (EAssetPropertyType) Type() protoreflect.EnumType {
	return &file_steammessages_econ_steamclient_proto_enumTypes[0]
}

func (x EAssetPropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EAssetPropertyType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EAssetPropertyType(num)
	return nil
}

// Deprecated: Use EAssetPropertyType.Descriptor instead.
func (EAssetPropertyType) EnumDescriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{0}
}

type CEcon_GetInventoryItemsWithDescriptions_Request struct {
	state                     protoimpl.MessageState                                         `protogen:"open.v1"`
	Steamid                   *uint64                                                        `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid                     *uint32                                                        `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	Contextid                 *uint64                                                        `protobuf:"varint,3,opt,name=contextid" json:"contextid,omitempty"`
	GetDescriptions           *bool                                                          `protobuf:"varint,4,opt,name=get_descriptions,json=getDescriptions" json:"get_descriptions,omitempty"`
	GetAssetProperties        *bool                                                          `protobuf:"varint,11,opt,name=get_asset_properties,json=getAssetProperties" json:"get_asset_properties,omitempty"`
	ForTradeOfferVerification *bool                                                          `protobuf:"varint,10,opt,name=for_trade_offer_verification,json=forTradeOfferVerification" json:"for_trade_offer_verification,omitempty"`
	Language                  *string                                                        `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
	Filters                   *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions `protobuf:"bytes,6,opt,name=filters" json:"filters,omitempty"`
	StartAssetid              *uint64                                                        `protobuf:"varint,8,opt,name=start_assetid,json=startAssetid" json:"start_assetid,omitempty"`
	Count                     *int32                                                         `protobuf:"varint,9,opt,name=count" json:"count,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) Reset() {
	*x = CEcon_GetInventoryItemsWithDescriptions_Request{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetInventoryItemsWithDescriptions_Request) ProtoMessage() {}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetInventoryItemsWithDescriptions_Request.ProtoReflect.Descriptor instead.
func (*CEcon_GetInventoryItemsWithDescriptions_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{0}
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetContextid() uint64 {
	if x != nil && x.Contextid != nil {
		return *x.Contextid
	}
	return 0
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetGetDescriptions() bool {
	if x != nil && x.GetDescriptions != nil {
		return *x.GetDescriptions
	}
	return false
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetGetAssetProperties() bool {
	if x != nil && x.GetAssetProperties != nil {
		return *x.GetAssetProperties
	}
	return false
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetForTradeOfferVerification() bool {
	if x != nil && x.ForTradeOfferVerification != nil {
		return *x.ForTradeOfferVerification
	}
	return false
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetFilters() *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetStartAssetid() uint64 {
	if x != nil && x.StartAssetid != nil {
		return *x.StartAssetid
	}
	return 0
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type CEcon_Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Contextid     *uint64                `protobuf:"varint,2,opt,name=contextid" json:"contextid,omitempty"`
	Assetid       *uint64                `protobuf:"varint,3,opt,name=assetid" json:"assetid,omitempty"`
	Classid       *uint64                `protobuf:"varint,4,opt,name=classid" json:"classid,omitempty"`
	Instanceid    *uint64                `protobuf:"varint,5,opt,name=instanceid" json:"instanceid,omitempty"`
	Currencyid    *uint32                `protobuf:"varint,6,opt,name=currencyid" json:"currencyid,omitempty"`
	Amount        *int64                 `protobuf:"varint,7,opt,name=amount" json:"amount,omitempty"`
	Missing       *bool                  `protobuf:"varint,8,opt,name=missing" json:"missing,omitempty"`
	EstUsd        *int64                 `protobuf:"varint,9,opt,name=est_usd,json=estUsd" json:"est_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEcon_Asset) Reset() {
	*x = CEcon_Asset{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_Asset) ProtoMessage() {}

func (x *CEcon_Asset) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_Asset.ProtoReflect.Descriptor instead.
func (*CEcon_Asset) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{1}
}

func (x *CEcon_Asset) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CEcon_Asset) GetContextid() uint64 {
	if x != nil && x.Contextid != nil {
		return *x.Contextid
	}
	return 0
}

func (x *CEcon_Asset) GetAssetid() uint64 {
	if x != nil && x.Assetid != nil {
		return *x.Assetid
	}
	return 0
}

func (x *CEcon_Asset) GetClassid() uint64 {
	if x != nil && x.Classid != nil {
		return *x.Classid
	}
	return 0
}

func (x *CEcon_Asset) GetInstanceid() uint64 {
	if x != nil && x.Instanceid != nil {
		return *x.Instanceid
	}
	return 0
}

func (x *CEcon_Asset) GetCurrencyid() uint32 {
	if x != nil && x.Currencyid != nil {
		return *x.Currencyid
	}
	return 0
}

func (x *CEcon_Asset) GetAmount() int64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *CEcon_Asset) GetMissing() bool {
	if x != nil && x.Missing != nil {
		return *x.Missing
	}
	return false
}

func (x *CEcon_Asset) GetEstUsd() int64 {
	if x != nil && x.EstUsd != nil {
		return *x.EstUsd
	}
	return 0
}

type CEconItem_DescriptionLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color" json:"color,omitempty"`
	Label         *string                `protobuf:"bytes,4,opt,name=label" json:"label,omitempty"`
	Name          *string                `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEconItem_DescriptionLine) Reset() {
	*x = CEconItem_DescriptionLine{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_DescriptionLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_DescriptionLine) ProtoMessage() {}

func (x *CEconItem_DescriptionLine) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_DescriptionLine.ProtoReflect.Descriptor instead.
func (*CEconItem_DescriptionLine) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{2}
}

func (x *CEconItem_DescriptionLine) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CEconItem_DescriptionLine) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *CEconItem_DescriptionLine) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *CEconItem_DescriptionLine) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *CEconItem_DescriptionLine) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type CEconItem_Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *string                `protobuf:"bytes,1,opt,name=link" json:"link,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEconItem_Action) Reset() {
	*x = CEconItem_Action{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_Action) ProtoMessage() {}

func (x *CEconItem_Action) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_Action.ProtoReflect.Descriptor instead.
func (*CEconItem_Action) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{3}
}

func (x *CEconItem_Action) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *CEconItem_Action) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type CEconItem_Description struct {
	state                        protoimpl.MessageState         `protogen:"open.v1"`
	Appid                        *int32                         `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Classid                      *uint64                        `protobuf:"varint,2,opt,name=classid" json:"classid,omitempty"`
	Instanceid                   *uint64                        `protobuf:"varint,3,opt,name=instanceid" json:"instanceid,omitempty"`
	Currency                     *bool                          `protobuf:"varint,4,opt,name=currency" json:"currency,omitempty"`
	BackgroundColor              *string                        `protobuf:"bytes,5,opt,name=background_color,json=backgroundColor" json:"background_color,omitempty"`
	IconUrl                      *string                        `protobuf:"bytes,6,opt,name=icon_url,json=iconUrl" json:"icon_url,omitempty"`
	IconUrlLarge                 *string                        `protobuf:"bytes,7,opt,name=icon_url_large,json=iconUrlLarge" json:"icon_url_large,omitempty"`
	Descriptions                 []*CEconItem_DescriptionLine   `protobuf:"bytes,8,rep,name=descriptions" json:"descriptions,omitempty"`
	Tradable                     *bool                          `protobuf:"varint,9,opt,name=tradable" json:"tradable,omitempty"`
	Actions                      []*CEconItem_Action            `protobuf:"bytes,10,rep,name=actions" json:"actions,omitempty"`
	OwnerDescriptions            []*CEconItem_DescriptionLine   `protobuf:"bytes,11,rep,name=owner_descriptions,json=ownerDescriptions" json:"owner_descriptions,omitempty"`
	OwnerActions                 []*CEconItem_Action            `protobuf:"bytes,12,rep,name=owner_actions,json=ownerActions" json:"owner_actions,omitempty"`
	Fraudwarnings                []string                       `protobuf:"bytes,13,rep,name=fraudwarnings" json:"fraudwarnings,omitempty"`
	Name                         *string                        `protobuf:"bytes,14,opt,name=name" json:"name,omitempty"`
	NameColor                    *string                        `protobuf:"bytes,15,opt,name=name_color,json=nameColor" json:"name_color,omitempty"`
	Type                         *string                        `protobuf:"bytes,16,opt,name=type" json:"type,omitempty"`
	MarketName                   *string                        `protobuf:"bytes,17,opt,name=market_name,json=marketName" json:"market_name,omitempty"`
	MarketHashName               *string                        `protobuf:"bytes,18,opt,name=market_hash_name,json=marketHashName" json:"market_hash_name,omitempty"`
	MarketFee                    *string                        `protobuf:"bytes,19,opt,name=market_fee,json=marketFee" json:"market_fee,omitempty"`
	MarketFeeApp                 *int32                         `protobuf:"varint,28,opt,name=market_fee_app,json=marketFeeApp" json:"market_fee_app,omitempty"`
	ContainedItem                *CEconItem_Description         `protobuf:"bytes,20,opt,name=contained_item,json=containedItem" json:"contained_item,omitempty"`
	MarketActions                []*CEconItem_Action            `protobuf:"bytes,21,rep,name=market_actions,json=marketActions" json:"market_actions,omitempty"`
	Commodity                    *bool                          `protobuf:"varint,22,opt,name=commodity" json:"commodity,omitempty"`
	MarketTradableRestriction    *int32                         `protobuf:"varint,23,opt,name=market_tradable_restriction,json=marketTradableRestriction" json:"market_tradable_restriction,omitempty"`
	MarketMarketableRestriction  *int32                         `protobuf:"varint,24,opt,name=market_marketable_restriction,json=marketMarketableRestriction" json:"market_marketable_restriction,omitempty"`
	Marketable                   *bool                          `protobuf:"varint,25,opt,name=marketable" json:"marketable,omitempty"`
	Tags                         []*CEconItem_Tag               `protobuf:"bytes,26,rep,name=tags" json:"tags,omitempty"`
	ItemExpiration               *string                        `protobuf:"bytes,27,opt,name=item_expiration,json=itemExpiration" json:"item_expiration,omitempty"`
	MarketBuyCountryRestriction  *string                        `protobuf:"bytes,30,opt,name=market_buy_country_restriction,json=marketBuyCountryRestriction" json:"market_buy_country_restriction,omitempty"`
	MarketSellCountryRestriction *string                        `protobuf:"bytes,31,opt,name=market_sell_country_restriction,json=marketSellCountryRestriction" json:"market_sell_country_restriction,omitempty"`
	Sealed                       *bool                          `protobuf:"varint,32,opt,name=sealed" json:"sealed,omitempty"`
	ContainerProperties          *CEconItem_ContainerProperties `protobuf:"bytes,33,opt,name=container_properties,json=containerProperties" json:"container_properties,omitempty"`
	MarketBucketGroupName        *string                        `protobuf:"bytes,34,opt,name=market_bucket_group_name,json=marketBucketGroupName" json:"market_bucket_group_name,omitempty"`
	MarketBucketGroupId          *string                        `protobuf:"bytes,35,opt,name=market_bucket_group_id,json=marketBucketGroupId" json:"market_bucket_group_id,omitempty"`
	SealedType                   *uint32                        `protobuf:"varint,37,opt,name=sealed_type,json=sealedType" json:"sealed_type,omitempty"`
	MarketNameInsideGroup        *string                        `protobuf:"bytes,38,opt,name=market_name_inside_group,json=marketNameInsideGroup" json:"market_name_inside_group,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CEconItem_Description) Reset() {
	*x = CEconItem_Description{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_Description) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_Description) ProtoMessage() {}

func (x *CEconItem_Description) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_Description.ProtoReflect.Descriptor instead.
func (*CEconItem_Description) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{4}
}

func (x *CEconItem_Description) GetAppid() int32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CEconItem_Description) GetClassid() uint64 {
	if x != nil && x.Classid != nil {
		return *x.Classid
	}
	return 0
}

func (x *CEconItem_Description) GetInstanceid() uint64 {
	if x != nil && x.Instanceid != nil {
		return *x.Instanceid
	}
	return 0
}

func (x *CEconItem_Description) GetCurrency() bool {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return false
}

func (x *CEconItem_Description) GetBackgroundColor() string {
	if x != nil && x.BackgroundColor != nil {
		return *x.BackgroundColor
	}
	return ""
}

func (x *CEconItem_Description) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *CEconItem_Description) GetIconUrlLarge() string {
	if x != nil && x.IconUrlLarge != nil {
		return *x.IconUrlLarge
	}
	return ""
}

func (x *CEconItem_Description) GetDescriptions() []*CEconItem_DescriptionLine {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *CEconItem_Description) GetTradable() bool {
	if x != nil && x.Tradable != nil {
		return *x.Tradable
	}
	return false
}

func (x *CEconItem_Description) GetActions() []*CEconItem_Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CEconItem_Description) GetOwnerDescriptions() []*CEconItem_DescriptionLine {
	if x != nil {
		return x.OwnerDescriptions
	}
	return nil
}

func (x *CEconItem_Description) GetOwnerActions() []*CEconItem_Action {
	if x != nil {
		return x.OwnerActions
	}
	return nil
}

func (x *CEconItem_Description) GetFraudwarnings() []string {
	if x != nil {
		return x.Fraudwarnings
	}
	return nil
}

func (x *CEconItem_Description) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CEconItem_Description) GetNameColor() string {
	if x != nil && x.NameColor != nil {
		return *x.NameColor
	}
	return ""
}

func (x *CEconItem_Description) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CEconItem_Description) GetMarketName() string {
	if x != nil && x.MarketName != nil {
		return *x.MarketName
	}
	return ""
}

func (x *CEconItem_Description) GetMarketHashName() string {
	if x != nil && x.MarketHashName != nil {
		return *x.MarketHashName
	}
	return ""
}

func (x *CEconItem_Description) GetMarketFee() string {
	if x != nil && x.MarketFee != nil {
		return *x.MarketFee
	}
	return ""
}

func (x *CEconItem_Description) GetMarketFeeApp() int32 {
	if x != nil && x.MarketFeeApp != nil {
		return *x.MarketFeeApp
	}
	return 0
}

func (x *CEconItem_Description) GetContainedItem() *CEconItem_Description {
	if x != nil {
		return x.ContainedItem
	}
	return nil
}

func (x *CEconItem_Description) GetMarketActions() []*CEconItem_Action {
	if x != nil {
		return x.MarketActions
	}
	return nil
}

func (x *CEconItem_Description) GetCommodity() bool {
	if x != nil && x.Commodity != nil {
		return *x.Commodity
	}
	return false
}

func (x *CEconItem_Description) GetMarketTradableRestriction() int32 {
	if x != nil && x.MarketTradableRestriction != nil {
		return *x.MarketTradableRestriction
	}
	return 0
}

func (x *CEconItem_Description) GetMarketMarketableRestriction() int32 {
	if x != nil && x.MarketMarketableRestriction != nil {
		return *x.MarketMarketableRestriction
	}
	return 0
}

func (x *CEconItem_Description) GetMarketable() bool {
	if x != nil && x.Marketable != nil {
		return *x.Marketable
	}
	return false
}

func (x *CEconItem_Description) GetTags() []*CEconItem_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CEconItem_Description) GetItemExpiration() string {
	if x != nil && x.ItemExpiration != nil {
		return *x.ItemExpiration
	}
	return ""
}

func (x *CEconItem_Description) GetMarketBuyCountryRestriction() string {
	if x != nil && x.MarketBuyCountryRestriction != nil {
		return *x.MarketBuyCountryRestriction
	}
	return ""
}

func (x *CEconItem_Description) GetMarketSellCountryRestriction() string {
	if x != nil && x.MarketSellCountryRestriction != nil {
		return *x.MarketSellCountryRestriction
	}
	return ""
}

func (x *CEconItem_Description) GetSealed() bool {
	if x != nil && x.Sealed != nil {
		return *x.Sealed
	}
	return false
}

func (x *CEconItem_Description) GetContainerProperties() *CEconItem_ContainerProperties {
	if x != nil {
		return x.ContainerProperties
	}
	return nil
}

func (x *CEconItem_Description) GetMarketBucketGroupName() string {
	if x != nil && x.MarketBucketGroupName != nil {
		return *x.MarketBucketGroupName
	}
	return ""
}

func (x *CEconItem_Description) GetMarketBucketGroupId() string {
	if x != nil && x.MarketBucketGroupId != nil {
		return *x.MarketBucketGroupId
	}
	return ""
}

func (x *CEconItem_Description) GetSealedType() uint32 {
	if x != nil && x.SealedType != nil {
		return *x.SealedType
	}
	return 0
}

func (x *CEconItem_Description) GetMarketNameInsideGroup() string {
	if x != nil && x.MarketNameInsideGroup != nil {
		return *x.MarketNameInsideGroup
	}
	return ""
}

type CEconItem_Tag struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Appid                 *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Category              *string                `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	InternalName          *string                `protobuf:"bytes,3,opt,name=internal_name,json=internalName" json:"internal_name,omitempty"`
	LocalizedCategoryName *string                `protobuf:"bytes,4,opt,name=localized_category_name,json=localizedCategoryName" json:"localized_category_name,omitempty"`
	LocalizedTagName      *string                `protobuf:"bytes,5,opt,name=localized_tag_name,json=localizedTagName" json:"localized_tag_name,omitempty"`
	Color                 *string                `protobuf:"bytes,6,opt,name=color" json:"color,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CEconItem_Tag) Reset() {
	*x = CEconItem_Tag{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_Tag) ProtoMessage() {}

func (x *CEconItem_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_Tag.ProtoReflect.Descriptor instead.
func (*CEconItem_Tag) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{5}
}

func (x *CEconItem_Tag) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CEconItem_Tag) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *CEconItem_Tag) GetInternalName() string {
	if x != nil && x.InternalName != nil {
		return *x.InternalName
	}
	return ""
}

func (x *CEconItem_Tag) GetLocalizedCategoryName() string {
	if x != nil && x.LocalizedCategoryName != nil {
		return *x.LocalizedCategoryName
	}
	return ""
}

func (x *CEconItem_Tag) GetLocalizedTagName() string {
	if x != nil && x.LocalizedTagName != nil {
		return *x.LocalizedTagName
	}
	return ""
}

func (x *CEconItem_Tag) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type CEconItem_ClassIdentifiers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classid       *uint64                `protobuf:"varint,1,opt,name=classid" json:"classid,omitempty"`
	Instanceid    *uint64                `protobuf:"varint,2,opt,name=instanceid" json:"instanceid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEconItem_ClassIdentifiers) Reset() {
	*x = CEconItem_ClassIdentifiers{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_ClassIdentifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_ClassIdentifiers) ProtoMessage() {}

func (x *CEconItem_ClassIdentifiers) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_ClassIdentifiers.ProtoReflect.Descriptor instead.
func (*CEconItem_ClassIdentifiers) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{6}
}

func (x *CEconItem_ClassIdentifiers) GetClassid() uint64 {
	if x != nil && x.Classid != nil {
		return *x.Classid
	}
	return 0
}

func (x *CEconItem_ClassIdentifiers) GetInstanceid() uint64 {
	if x != nil && x.Instanceid != nil {
		return *x.Instanceid
	}
	return 0
}

type CEconItem_ContainerProperties struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	ContainedItems []*CEconItem_ClassIdentifiers `protobuf:"bytes,1,rep,name=contained_items,json=containedItems" json:"contained_items,omitempty"`
	SearchTags     []*CEconItem_Tag              `protobuf:"bytes,2,rep,name=search_tags,json=searchTags" json:"search_tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CEconItem_ContainerProperties) Reset() {
	*x = CEconItem_ContainerProperties{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_ContainerProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_ContainerProperties) ProtoMessage() {}

func (x *CEconItem_ContainerProperties) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_ContainerProperties.ProtoReflect.Descriptor instead.
func (*CEconItem_ContainerProperties) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{7}
}

func (x *CEconItem_ContainerProperties) GetContainedItems() []*CEconItem_ClassIdentifiers {
	if x != nil {
		return x.ContainedItems
	}
	return nil
}

func (x *CEconItem_ContainerProperties) GetSearchTags() []*CEconItem_Tag {
	if x != nil {
		return x.SearchTags
	}
	return nil
}

type CEconItem_AssetProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Propertyid    *uint32                `protobuf:"varint,1,opt,name=propertyid" json:"propertyid,omitempty"`
	IntValue      *int64                 `protobuf:"varint,2,opt,name=int_value,json=intValue" json:"int_value,omitempty"`
	FloatValue    *float32               `protobuf:"fixed32,3,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	StringValue   *string                `protobuf:"bytes,4,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEconItem_AssetProperty) Reset() {
	*x = CEconItem_AssetProperty{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_AssetProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_AssetProperty) ProtoMessage() {}

func (x *CEconItem_AssetProperty) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_AssetProperty.ProtoReflect.Descriptor instead.
func (*CEconItem_AssetProperty) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{8}
}

func (x *CEconItem_AssetProperty) GetPropertyid() uint32 {
	if x != nil && x.Propertyid != nil {
		return *x.Propertyid
	}
	return 0
}

func (x *CEconItem_AssetProperty) GetIntValue() int64 {
	if x != nil && x.IntValue != nil {
		return *x.IntValue
	}
	return 0
}

func (x *CEconItem_AssetProperty) GetFloatValue() float32 {
	if x != nil && x.FloatValue != nil {
		return *x.FloatValue
	}
	return 0
}

func (x *CEconItem_AssetProperty) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

type CEconItem_AssetAccessory struct {
	state                        protoimpl.MessageState      `protogen:"open.v1"`
	Classid                      *uint64                     `protobuf:"varint,1,opt,name=classid" json:"classid,omitempty"`
	Instanceid                   *uint64                     `protobuf:"varint,2,opt,name=instanceid" json:"instanceid,omitempty"`
	StandaloneProperties         []*CEconItem_AssetProperty  `protobuf:"bytes,3,rep,name=standalone_properties,json=standaloneProperties" json:"standalone_properties,omitempty"`
	ParentRelationshipProperties []*CEconItem_AssetProperty  `protobuf:"bytes,4,rep,name=parent_relationship_properties,json=parentRelationshipProperties" json:"parent_relationship_properties,omitempty"`
	NestedAccessories            []*CEconItem_AssetAccessory `protobuf:"bytes,5,rep,name=nested_accessories,json=nestedAccessories" json:"nested_accessories,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CEconItem_AssetAccessory) Reset() {
	*x = CEconItem_AssetAccessory{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_AssetAccessory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_AssetAccessory) ProtoMessage() {}

func (x *CEconItem_AssetAccessory) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_AssetAccessory.ProtoReflect.Descriptor instead.
func (*CEconItem_AssetAccessory) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{9}
}

func (x *CEconItem_AssetAccessory) GetClassid() uint64 {
	if x != nil && x.Classid != nil {
		return *x.Classid
	}
	return 0
}

func (x *CEconItem_AssetAccessory) GetInstanceid() uint64 {
	if x != nil && x.Instanceid != nil {
		return *x.Instanceid
	}
	return 0
}

func (x *CEconItem_AssetAccessory) GetStandaloneProperties() []*CEconItem_AssetProperty {
	if x != nil {
		return x.StandaloneProperties
	}
	return nil
}

func (x *CEconItem_AssetAccessory) GetParentRelationshipProperties() []*CEconItem_AssetProperty {
	if x != nil {
		return x.ParentRelationshipProperties
	}
	return nil
}

func (x *CEconItem_AssetAccessory) GetNestedAccessories() []*CEconItem_AssetAccessory {
	if x != nil {
		return x.NestedAccessories
	}
	return nil
}

type CEconItem_AssetProperties struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	Appid            *uint32                     `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Contextid        *uint64                     `protobuf:"varint,2,opt,name=contextid" json:"contextid,omitempty"`
	Assetid          *uint64                     `protobuf:"varint,3,opt,name=assetid" json:"assetid,omitempty"`
	AssetProperties  []*CEconItem_AssetProperty  `protobuf:"bytes,4,rep,name=asset_properties,json=assetProperties" json:"asset_properties,omitempty"`
	AssetAccessories []*CEconItem_AssetAccessory `protobuf:"bytes,5,rep,name=asset_accessories,json=assetAccessories" json:"asset_accessories,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CEconItem_AssetProperties) Reset() {
	*x = CEconItem_AssetProperties{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_AssetProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_AssetProperties) ProtoMessage() {}

func (x *CEconItem_AssetProperties) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_AssetProperties.ProtoReflect.Descriptor instead.
func (*CEconItem_AssetProperties) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{10}
}

func (x *CEconItem_AssetProperties) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CEconItem_AssetProperties) GetContextid() uint64 {
	if x != nil && x.Contextid != nil {
		return *x.Contextid
	}
	return 0
}

func (x *CEconItem_AssetProperties) GetAssetid() uint64 {
	if x != nil && x.Assetid != nil {
		return *x.Assetid
	}
	return 0
}

func (x *CEconItem_AssetProperties) GetAssetProperties() []*CEconItem_AssetProperty {
	if x != nil {
		return x.AssetProperties
	}
	return nil
}

func (x *CEconItem_AssetProperties) GetAssetAccessories() []*CEconItem_AssetAccessory {
	if x != nil {
		return x.AssetAccessories
	}
	return nil
}

type CEcon_GetInventoryItemsWithDescriptions_Response struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	Assets              []*CEcon_Asset               `protobuf:"bytes,1,rep,name=assets" json:"assets,omitempty"`
	Descriptions        []*CEconItem_Description     `protobuf:"bytes,2,rep,name=descriptions" json:"descriptions,omitempty"`
	MissingAssets       []*CEcon_Asset               `protobuf:"bytes,3,rep,name=missing_assets,json=missingAssets" json:"missing_assets,omitempty"`
	AssetProperties     []*CEconItem_AssetProperties `protobuf:"bytes,7,rep,name=asset_properties,json=assetProperties" json:"asset_properties,omitempty"`
	MoreItems           *bool                        `protobuf:"varint,4,opt,name=more_items,json=moreItems" json:"more_items,omitempty"`
	LastAssetid         *uint64                      `protobuf:"varint,5,opt,name=last_assetid,json=lastAssetid" json:"last_assetid,omitempty"`
	TotalInventoryCount *uint32                      `protobuf:"varint,6,opt,name=total_inventory_count,json=totalInventoryCount" json:"total_inventory_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) Reset() {
	*x = CEcon_GetInventoryItemsWithDescriptions_Response{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetInventoryItemsWithDescriptions_Response) ProtoMessage() {}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetInventoryItemsWithDescriptions_Response.ProtoReflect.Descriptor instead.
func (*CEcon_GetInventoryItemsWithDescriptions_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{11}
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) GetAssets() []*CEcon_Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) GetDescriptions() []*CEconItem_Description {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) GetMissingAssets() []*CEcon_Asset {
	if x != nil {
		return x.MissingAssets
	}
	return nil
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) GetAssetProperties() []*CEconItem_AssetProperties {
	if x != nil {
		return x.AssetProperties
	}
	return nil
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) GetMoreItems() bool {
	if x != nil && x.MoreItems != nil {
		return *x.MoreItems
	}
	return false
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) GetLastAssetid() uint64 {
	if x != nil && x.LastAssetid != nil {
		return *x.LastAssetid
	}
	return 0
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Response) GetTotalInventoryCount() uint32 {
	if x != nil && x.TotalInventoryCount != nil {
		return *x.TotalInventoryCount
	}
	return 0
}

type CEcon_GetTradeOfferAccessToken_Request struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GenerateNewToken *bool                  `protobuf:"varint,1,opt,name=generate_new_token,json=generateNewToken" json:"generate_new_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CEcon_GetTradeOfferAccessToken_Request) Reset() {
	*x = CEcon_GetTradeOfferAccessToken_Request{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetTradeOfferAccessToken_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetTradeOfferAccessToken_Request) ProtoMessage() {}

func (x *CEcon_GetTradeOfferAccessToken_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetTradeOfferAccessToken_Request.ProtoReflect.Descriptor instead.
func (*CEcon_GetTradeOfferAccessToken_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{12}
}

func (x *CEcon_GetTradeOfferAccessToken_Request) GetGenerateNewToken() bool {
	if x != nil && x.GenerateNewToken != nil {
		return *x.GenerateNewToken
	}
	return false
}

type CEcon_GetTradeOfferAccessToken_Response struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TradeOfferAccessToken *string                `protobuf:"bytes,1,opt,name=trade_offer_access_token,json=tradeOfferAccessToken" json:"trade_offer_access_token,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CEcon_GetTradeOfferAccessToken_Response) Reset() {
	*x = CEcon_GetTradeOfferAccessToken_Response{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetTradeOfferAccessToken_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetTradeOfferAccessToken_Response) ProtoMessage() {}

func (x *CEcon_GetTradeOfferAccessToken_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetTradeOfferAccessToken_Response.ProtoReflect.Descriptor instead.
func (*CEcon_GetTradeOfferAccessToken_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{13}
}

func (x *CEcon_GetTradeOfferAccessToken_Response) GetTradeOfferAccessToken() string {
	if x != nil && x.TradeOfferAccessToken != nil {
		return *x.TradeOfferAccessToken
	}
	return ""
}

type CEcon_ClientGetItemShopOverlayAuthURL_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnUrl     *string                `protobuf:"bytes,1,opt,name=return_url,json=returnUrl" json:"return_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEcon_ClientGetItemShopOverlayAuthURL_Request) Reset() {
	*x = CEcon_ClientGetItemShopOverlayAuthURL_Request{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_ClientGetItemShopOverlayAuthURL_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_ClientGetItemShopOverlayAuthURL_Request) ProtoMessage() {}

func (x *CEcon_ClientGetItemShopOverlayAuthURL_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_ClientGetItemShopOverlayAuthURL_Request.ProtoReflect.Descriptor instead.
func (*CEcon_ClientGetItemShopOverlayAuthURL_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{14}
}

func (x *CEcon_ClientGetItemShopOverlayAuthURL_Request) GetReturnUrl() string {
	if x != nil && x.ReturnUrl != nil {
		return *x.ReturnUrl
	}
	return ""
}

type CEcon_ClientGetItemShopOverlayAuthURL_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEcon_ClientGetItemShopOverlayAuthURL_Response) Reset() {
	*x = CEcon_ClientGetItemShopOverlayAuthURL_Response{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_ClientGetItemShopOverlayAuthURL_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_ClientGetItemShopOverlayAuthURL_Response) ProtoMessage() {}

func (x *CEcon_ClientGetItemShopOverlayAuthURL_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_ClientGetItemShopOverlayAuthURL_Response.ProtoReflect.Descriptor instead.
func (*CEcon_ClientGetItemShopOverlayAuthURL_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{15}
}

func (x *CEcon_ClientGetItemShopOverlayAuthURL_Response) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type CEcon_GetAssetClassInfo_Request struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Language      *string                       `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
	Appid         *uint32                       `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	Classes       []*CEconItem_ClassIdentifiers `protobuf:"bytes,3,rep,name=classes" json:"classes,omitempty"`
	HighPri       *bool                         `protobuf:"varint,4,opt,name=high_pri,json=highPri" json:"high_pri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEcon_GetAssetClassInfo_Request) Reset() {
	*x = CEcon_GetAssetClassInfo_Request{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetAssetClassInfo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetAssetClassInfo_Request) ProtoMessage() {}

func (x *CEcon_GetAssetClassInfo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetAssetClassInfo_Request.ProtoReflect.Descriptor instead.
func (*CEcon_GetAssetClassInfo_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{16}
}

func (x *CEcon_GetAssetClassInfo_Request) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *CEcon_GetAssetClassInfo_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CEcon_GetAssetClassInfo_Request) GetClasses() []*CEconItem_ClassIdentifiers {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *CEcon_GetAssetClassInfo_Request) GetHighPri() bool {
	if x != nil && x.HighPri != nil {
		return *x.HighPri
	}
	return false
}

type CEcon_GetAssetClassInfo_Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Descriptions  []*CEconItem_Description `protobuf:"bytes,1,rep,name=descriptions" json:"descriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEcon_GetAssetClassInfo_Response) Reset() {
	*x = CEcon_GetAssetClassInfo_Response{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetAssetClassInfo_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetAssetClassInfo_Response) ProtoMessage() {}

func (x *CEcon_GetAssetClassInfo_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetAssetClassInfo_Response.ProtoReflect.Descriptor instead.
func (*CEcon_GetAssetClassInfo_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{17}
}

func (x *CEcon_GetAssetClassInfo_Response) GetDescriptions() []*CEconItem_Description {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

type CEcon_GetAssetPropertySchema_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Language      *string                `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEcon_GetAssetPropertySchema_Request) Reset() {
	*x = CEcon_GetAssetPropertySchema_Request{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetAssetPropertySchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetAssetPropertySchema_Request) ProtoMessage() {}

func (x *CEcon_GetAssetPropertySchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetAssetPropertySchema_Request.ProtoReflect.Descriptor instead.
func (*CEcon_GetAssetPropertySchema_Request) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{18}
}

func (x *CEcon_GetAssetPropertySchema_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CEcon_GetAssetPropertySchema_Request) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type CEconItem_AssetPropertySchema struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type                *EAssetPropertyType    `protobuf:"varint,3,opt,name=type,enum=EAssetPropertyType,def=0" json:"type,omitempty"`
	FloatMin            *float32               `protobuf:"fixed32,4,opt,name=float_min,json=floatMin" json:"float_min,omitempty"`
	FloatMax            *float32               `protobuf:"fixed32,5,opt,name=float_max,json=floatMax" json:"float_max,omitempty"`
	IntMin              *int64                 `protobuf:"varint,6,opt,name=int_min,json=intMin" json:"int_min,omitempty"`
	IntMax              *int64                 `protobuf:"varint,7,opt,name=int_max,json=intMax" json:"int_max,omitempty"`
	LocalizedLabel      *string                `protobuf:"bytes,8,opt,name=localized_label,json=localizedLabel" json:"localized_label,omitempty"`
	HideFromDescription *bool                  `protobuf:"varint,9,opt,name=hide_from_description,json=hideFromDescription" json:"hide_from_description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

// Default values for CEconItem_AssetPropertySchema fields.
const (
	Default_CEconItem_AssetPropertySchema_Type = EAssetPropertyType_k_EAssetPropertyType_Unknown
)

func (x *CEconItem_AssetPropertySchema) Reset() {
	*x = CEconItem_AssetPropertySchema{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEconItem_AssetPropertySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEconItem_AssetPropertySchema) ProtoMessage() {}

func (x *CEconItem_AssetPropertySchema) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEconItem_AssetPropertySchema.ProtoReflect.Descriptor instead.
func (*CEconItem_AssetPropertySchema) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{19}
}

func (x *CEconItem_AssetPropertySchema) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CEconItem_AssetPropertySchema) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CEconItem_AssetPropertySchema) GetType() EAssetPropertyType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_CEconItem_AssetPropertySchema_Type
}

func (x *CEconItem_AssetPropertySchema) GetFloatMin() float32 {
	if x != nil && x.FloatMin != nil {
		return *x.FloatMin
	}
	return 0
}

func (x *CEconItem_AssetPropertySchema) GetFloatMax() float32 {
	if x != nil && x.FloatMax != nil {
		return *x.FloatMax
	}
	return 0
}

func (x *CEconItem_AssetPropertySchema) GetIntMin() int64 {
	if x != nil && x.IntMin != nil {
		return *x.IntMin
	}
	return 0
}

func (x *CEconItem_AssetPropertySchema) GetIntMax() int64 {
	if x != nil && x.IntMax != nil {
		return *x.IntMax
	}
	return 0
}

func (x *CEconItem_AssetPropertySchema) GetLocalizedLabel() string {
	if x != nil && x.LocalizedLabel != nil {
		return *x.LocalizedLabel
	}
	return ""
}

func (x *CEconItem_AssetPropertySchema) GetHideFromDescription() bool {
	if x != nil && x.HideFromDescription != nil {
		return *x.HideFromDescription
	}
	return false
}

type CEcon_GetAssetPropertySchema_Response struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	PropertySchemas []*CEconItem_AssetPropertySchema `protobuf:"bytes,1,rep,name=property_schemas,json=propertySchemas" json:"property_schemas,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CEcon_GetAssetPropertySchema_Response) Reset() {
	*x = CEcon_GetAssetPropertySchema_Response{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetAssetPropertySchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetAssetPropertySchema_Response) ProtoMessage() {}

func (x *CEcon_GetAssetPropertySchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetAssetPropertySchema_Response.ProtoReflect.Descriptor instead.
func (*CEcon_GetAssetPropertySchema_Response) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{20}
}

func (x *CEcon_GetAssetPropertySchema_Response) GetPropertySchemas() []*CEconItem_AssetPropertySchema {
	if x != nil {
		return x.PropertySchemas
	}
	return nil
}

type CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Assetids       []uint64               `protobuf:"varint,1,rep,name=assetids" json:"assetids,omitempty"`
	Currencyids    []uint32               `protobuf:"varint,2,rep,name=currencyids" json:"currencyids,omitempty"`
	TradableOnly   *bool                  `protobuf:"varint,3,opt,name=tradable_only,json=tradableOnly" json:"tradable_only,omitempty"`
	MarketableOnly *bool                  `protobuf:"varint,4,opt,name=marketable_only,json=marketableOnly" json:"marketable_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) Reset() {
	*x = CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions{}
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) ProtoMessage() {}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) ProtoReflect() protoreflect.Message {
	mi := &file_steammessages_econ_steamclient_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions.ProtoReflect.Descriptor instead.
func (*CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) Descriptor() ([]byte, []int) {
	return file_steammessages_econ_steamclient_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) GetAssetids() []uint64 {
	if x != nil {
		return x.Assetids
	}
	return nil
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) GetCurrencyids() []uint32 {
	if x != nil {
		return x.Currencyids
	}
	return nil
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) GetTradableOnly() bool {
	if x != nil && x.TradableOnly != nil {
		return *x.TradableOnly
	}
	return false
}

func (x *CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions) GetMarketableOnly() bool {
	if x != nil && x.MarketableOnly != nil {
		return *x.MarketableOnly
	}
	return false
}

var File_steammessages_econ_steamclient_proto protoreflect.FileDescriptor

const file_steammessages_econ_steamclient_proto_rawDesc = "" +
	"\n" +
	"$steammessages_econ.steamclient.proto\x1a\x18steammessages_base.proto\x1a,steammessages_unified_base.steamclient.proto\"\xec\x04\n" +
	"/CEcon_GetInventoryItemsWithDescriptions_Request\x12\x18\n" +
	"\asteamid\x18\x01 \x01(\x06R\asteamid\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\rR\x05appid\x12\x1c\n" +
	"\tcontextid\x18\x03 \x01(\x04R\tcontextid\x12)\n" +
	"\x10get_descriptions\x18\x04 \x01(\bR\x0fgetDescriptions\x120\n" +
	"\x14get_asset_properties\x18\v \x01(\bR\x12getAssetProperties\x12?\n" +
	"\x1cfor_trade_offer_verification\x18\n" +
	" \x01(\bR\x19forTradeOfferVerification\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12X\n" +
	"\afilters\x18\x06 \x01(\v2>.CEcon_GetInventoryItemsWithDescriptions_Request.FilterOptionsR\afilters\x12#\n" +
	"\rstart_assetid\x18\b \x01(\x04R\fstartAssetid\x12\x14\n" +
	"\x05count\x18\t \x01(\x05R\x05count\x1a\x9b\x01\n" +
	"\rFilterOptions\x12\x1a\n" +
	"\bassetids\x18\x01 \x03(\x04R\bassetids\x12 \n" +
	"\vcurrencyids\x18\x02 \x03(\rR\vcurrencyids\x12#\n" +
	"\rtradable_only\x18\x03 \x01(\bR\ftradableOnly\x12'\n" +
	"\x0fmarketable_only\x18\x04 \x01(\bR\x0emarketableOnly\"\x80\x02\n" +
	"\vCEcon_Asset\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x1c\n" +
	"\tcontextid\x18\x02 \x01(\x04R\tcontextid\x12\x18\n" +
	"\aassetid\x18\x03 \x01(\x04R\aassetid\x12\x18\n" +
	"\aclassid\x18\x04 \x01(\x04R\aclassid\x12\x1e\n" +
	"\n" +
	"instanceid\x18\x05 \x01(\x04R\n" +
	"instanceid\x12\x1e\n" +
	"\n" +
	"currencyid\x18\x06 \x01(\rR\n" +
	"currencyid\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x18\n" +
	"\amissing\x18\b \x01(\bR\amissing\x12\x17\n" +
	"\aest_usd\x18\t \x01(\x03R\x06estUsd\"\x85\x01\n" +
	"\x19CEconItem_DescriptionLine\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\":\n" +
	"\x10CEconItem_Action\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xbf\f\n" +
	"\x15CEconItem_Description\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\x05R\x05appid\x12\x18\n" +
	"\aclassid\x18\x02 \x01(\x04R\aclassid\x12\x1e\n" +
	"\n" +
	"instanceid\x18\x03 \x01(\x04R\n" +
	"instanceid\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\bR\bcurrency\x12)\n" +
	"\x10background_color\x18\x05 \x01(\tR\x0fbackgroundColor\x12\x19\n" +
	"\bicon_url\x18\x06 \x01(\tR\aiconUrl\x12$\n" +
	"\x0eicon_url_large\x18\a \x01(\tR\ficonUrlLarge\x12>\n" +
	"\fdescriptions\x18\b \x03(\v2\x1a.CEconItem_DescriptionLineR\fdescriptions\x12\x1a\n" +
	"\btradable\x18\t \x01(\bR\btradable\x12+\n" +
	"\aactions\x18\n" +
	" \x03(\v2\x11.CEconItem_ActionR\aactions\x12I\n" +
	"\x12owner_descriptions\x18\v \x03(\v2\x1a.CEconItem_DescriptionLineR\x11ownerDescriptions\x126\n" +
	"\rowner_actions\x18\f \x03(\v2\x11.CEconItem_ActionR\fownerActions\x12$\n" +
	"\rfraudwarnings\x18\r \x03(\tR\rfraudwarnings\x12\x12\n" +
	"\x04name\x18\x0e \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"name_color\x18\x0f \x01(\tR\tnameColor\x12\x12\n" +
	"\x04type\x18\x10 \x01(\tR\x04type\x12\x1f\n" +
	"\vmarket_name\x18\x11 \x01(\tR\n" +
	"marketName\x12(\n" +
	"\x10market_hash_name\x18\x12 \x01(\tR\x0emarketHashName\x12\x1d\n" +
	"\n" +
	"market_fee\x18\x13 \x01(\tR\tmarketFee\x12$\n" +
	"\x0emarket_fee_app\x18\x1c \x01(\x05R\fmarketFeeApp\x12=\n" +
	"\x0econtained_item\x18\x14 \x01(\v2\x16.CEconItem_DescriptionR\rcontainedItem\x128\n" +
	"\x0emarket_actions\x18\x15 \x03(\v2\x11.CEconItem_ActionR\rmarketActions\x12\x1c\n" +
	"\tcommodity\x18\x16 \x01(\bR\tcommodity\x12>\n" +
	"\x1bmarket_tradable_restriction\x18\x17 \x01(\x05R\x19marketTradableRestriction\x12B\n" +
	"\x1dmarket_marketable_restriction\x18\x18 \x01(\x05R\x1bmarketMarketableRestriction\x12\x1e\n" +
	"\n" +
	"marketable\x18\x19 \x01(\bR\n" +
	"marketable\x12\"\n" +
	"\x04tags\x18\x1a \x03(\v2\x0e.CEconItem_TagR\x04tags\x12'\n" +
	"\x0fitem_expiration\x18\x1b \x01(\tR\x0eitemExpiration\x12C\n" +
	"\x1emarket_buy_country_restriction\x18\x1e \x01(\tR\x1bmarketBuyCountryRestriction\x12E\n" +
	"\x1fmarket_sell_country_restriction\x18\x1f \x01(\tR\x1cmarketSellCountryRestriction\x12\x16\n" +
	"\x06sealed\x18  \x01(\bR\x06sealed\x12Q\n" +
	"\x14container_properties\x18! \x01(\v2\x1e.CEconItem_ContainerPropertiesR\x13containerProperties\x127\n" +
	"\x18market_bucket_group_name\x18\" \x01(\tR\x15marketBucketGroupName\x123\n" +
	"\x16market_bucket_group_id\x18# \x01(\tR\x13marketBucketGroupId\x12\x1f\n" +
	"\vsealed_type\x18% \x01(\rR\n" +
	"sealedType\x127\n" +
	"\x18market_name_inside_group\x18& \x01(\tR\x15marketNameInsideGroup\"\xe2\x01\n" +
	"\rCEconItem_Tag\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12#\n" +
	"\rinternal_name\x18\x03 \x01(\tR\finternalName\x126\n" +
	"\x17localized_category_name\x18\x04 \x01(\tR\x15localizedCategoryName\x12,\n" +
	"\x12localized_tag_name\x18\x05 \x01(\tR\x10localizedTagName\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\"V\n" +
	"\x1aCEconItem_ClassIdentifiers\x12\x18\n" +
	"\aclassid\x18\x01 \x01(\x04R\aclassid\x12\x1e\n" +
	"\n" +
	"instanceid\x18\x02 \x01(\x04R\n" +
	"instanceid\"\x96\x01\n" +
	"\x1dCEconItem_ContainerProperties\x12D\n" +
	"\x0fcontained_items\x18\x01 \x03(\v2\x1b.CEconItem_ClassIdentifiersR\x0econtainedItems\x12/\n" +
	"\vsearch_tags\x18\x02 \x03(\v2\x0e.CEconItem_TagR\n" +
	"searchTags\"\x9a\x01\n" +
	"\x17CEconItem_AssetProperty\x12\x1e\n" +
	"\n" +
	"propertyid\x18\x01 \x01(\rR\n" +
	"propertyid\x12\x1b\n" +
	"\tint_value\x18\x02 \x01(\x03R\bintValue\x12\x1f\n" +
	"\vfloat_value\x18\x03 \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fstring_value\x18\x04 \x01(\tR\vstringValue\"\xcd\x02\n" +
	"\x18CEconItem_AssetAccessory\x12\x18\n" +
	"\aclassid\x18\x01 \x01(\x04R\aclassid\x12\x1e\n" +
	"\n" +
	"instanceid\x18\x02 \x01(\x04R\n" +
	"instanceid\x12M\n" +
	"\x15standalone_properties\x18\x03 \x03(\v2\x18.CEconItem_AssetPropertyR\x14standaloneProperties\x12^\n" +
	"\x1eparent_relationship_properties\x18\x04 \x03(\v2\x18.CEconItem_AssetPropertyR\x1cparentRelationshipProperties\x12H\n" +
	"\x12nested_accessories\x18\x05 \x03(\v2\x19.CEconItem_AssetAccessoryR\x11nestedAccessories\"\xf6\x01\n" +
	"\x19CEconItem_AssetProperties\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x1c\n" +
	"\tcontextid\x18\x02 \x01(\x04R\tcontextid\x12\x18\n" +
	"\aassetid\x18\x03 \x01(\x04R\aassetid\x12C\n" +
	"\x10asset_properties\x18\x04 \x03(\v2\x18.CEconItem_AssetPropertyR\x0fassetProperties\x12F\n" +
	"\x11asset_accessories\x18\x05 \x03(\v2\x19.CEconItem_AssetAccessoryR\x10assetAccessories\"\x86\x03\n" +
	"0CEcon_GetInventoryItemsWithDescriptions_Response\x12$\n" +
	"\x06assets\x18\x01 \x03(\v2\f.CEcon_AssetR\x06assets\x12:\n" +
	"\fdescriptions\x18\x02 \x03(\v2\x16.CEconItem_DescriptionR\fdescriptions\x123\n" +
	"\x0emissing_assets\x18\x03 \x03(\v2\f.CEcon_AssetR\rmissingAssets\x12E\n" +
	"\x10asset_properties\x18\a \x03(\v2\x1a.CEconItem_AssetPropertiesR\x0fassetProperties\x12\x1d\n" +
	"\n" +
	"more_items\x18\x04 \x01(\bR\tmoreItems\x12!\n" +
	"\flast_assetid\x18\x05 \x01(\x04R\vlastAssetid\x122\n" +
	"\x15total_inventory_count\x18\x06 \x01(\rR\x13totalInventoryCount\"V\n" +
	"&CEcon_GetTradeOfferAccessToken_Request\x12,\n" +
	"\x12generate_new_token\x18\x01 \x01(\bR\x10generateNewToken\"b\n" +
	"'CEcon_GetTradeOfferAccessToken_Response\x127\n" +
	"\x18trade_offer_access_token\x18\x01 \x01(\tR\x15tradeOfferAccessToken\"N\n" +
	"-CEcon_ClientGetItemShopOverlayAuthURL_Request\x12\x1d\n" +
	"\n" +
	"return_url\x18\x01 \x01(\tR\treturnUrl\"B\n" +
	".CEcon_ClientGetItemShopOverlayAuthURL_Response\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xa5\x01\n" +
	"\x1fCEcon_GetAssetClassInfo_Request\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\rR\x05appid\x125\n" +
	"\aclasses\x18\x03 \x03(\v2\x1b.CEconItem_ClassIdentifiersR\aclasses\x12\x19\n" +
	"\bhigh_pri\x18\x04 \x01(\bR\ahighPri\"^\n" +
	" CEcon_GetAssetClassInfo_Response\x12:\n" +
	"\fdescriptions\x18\x01 \x03(\v2\x16.CEconItem_DescriptionR\fdescriptions\"X\n" +
	"$CEcon_GetAssetPropertySchema_Request\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"\xd3\x02\n" +
	"\x1dCEconItem_AssetPropertySchema\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12E\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.EAssetPropertyType:\x1ck_EAssetPropertyType_UnknownR\x04type\x12\x1b\n" +
	"\tfloat_min\x18\x04 \x01(\x02R\bfloatMin\x12\x1b\n" +
	"\tfloat_max\x18\x05 \x01(\x02R\bfloatMax\x12\x17\n" +
	"\aint_min\x18\x06 \x01(\x03R\x06intMin\x12\x17\n" +
	"\aint_max\x18\a \x01(\x03R\x06intMax\x12'\n" +
	"\x0flocalized_label\x18\b \x01(\tR\x0elocalizedLabel\x122\n" +
	"\x15hide_from_description\x18\t \x01(\bR\x13hideFromDescription\"r\n" +
	"%CEcon_GetAssetPropertySchema_Response\x12I\n" +
	"\x10property_schemas\x18\x01 \x03(\v2\x1e.CEconItem_AssetPropertySchemaR\x0fpropertySchemas*\xb3\x01\n" +
	"\x12EAssetPropertyType\x12 \n" +
	"\x1ck_EAssetPropertyType_Unknown\x10\x00\x12\x1e\n" +
	"\x1ak_EAssetPropertyType_Float\x10\x01\x12\x1c\n" +
	"\x18k_EAssetPropertyType_Int\x10\x02\x12\x1f\n" +
	"\x1bk_EAssetPropertyType_String\x10\x03\x12\x1c\n" +
	"\x18k_EAssetPropertyType_MAX\x10\x042\xc8\x04\n" +
	"\x04Econ\x12\x88\x01\n" +
	"!GetInventoryItemsWithDescriptions\x120.CEcon_GetInventoryItemsWithDescriptions_Request\x1a1.CEcon_GetInventoryItemsWithDescriptions_Response\x12m\n" +
	"\x18GetTradeOfferAccessToken\x12'.CEcon_GetTradeOfferAccessToken_Request\x1a(.CEcon_GetTradeOfferAccessToken_Response\x12\x82\x01\n" +
	"\x1fClientGetItemShopOverlayAuthURL\x12..CEcon_ClientGetItemShopOverlayAuthURL_Request\x1a/.CEcon_ClientGetItemShopOverlayAuthURL_Response\x12X\n" +
	"\x11GetAssetClassInfo\x12 .CEcon_GetAssetClassInfo_Request\x1a!.CEcon_GetAssetClassInfo_Response\x12g\n" +
	"\x16GetAssetPropertySchema\x12%.CEcon_GetAssetPropertySchema_Request\x1a&.CEcon_GetAssetPropertySchema_ResponseB\x03\x80\x01\x01"

var (
	file_steammessages_econ_steamclient_proto_rawDescOnce sync.Once
	file_steammessages_econ_steamclient_proto_rawDescData []byte
)

func file_steammessages_econ_steamclient_proto_rawDescGZIP() []byte {
	file_steammessages_econ_steamclient_proto_rawDescOnce.Do(func() {
		file_steammessages_econ_steamclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steammessages_econ_steamclient_proto_rawDesc), len(file_steammessages_econ_steamclient_proto_rawDesc)))
	})
	return file_steammessages_econ_steamclient_proto_rawDescData
}

var file_steammessages_econ_steamclient_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steammessages_econ_steamclient_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_steammessages_econ_steamclient_proto_goTypes = []any{
	(EAssetPropertyType)(0),                                               // 0: EAssetPropertyType
	(*CEcon_GetInventoryItemsWithDescriptions_Request)(nil),               // 1: CEcon_GetInventoryItemsWithDescriptions_Request
	(*CEcon_Asset)(nil),                                                   // 2: CEcon_Asset
	(*CEconItem_DescriptionLine)(nil),                                     // 3: CEconItem_DescriptionLine
	(*CEconItem_Action)(nil),                                              // 4: CEconItem_Action
	(*CEconItem_Description)(nil),                                         // 5: CEconItem_Description
	(*CEconItem_Tag)(nil),                                                 // 6: CEconItem_Tag
	(*CEconItem_ClassIdentifiers)(nil),                                    // 7: CEconItem_ClassIdentifiers
	(*CEconItem_ContainerProperties)(nil),                                 // 8: CEconItem_ContainerProperties
	(*CEconItem_AssetProperty)(nil),                                       // 9: CEconItem_AssetProperty
	(*CEconItem_AssetAccessory)(nil),                                      // 10: CEconItem_AssetAccessory
	(*CEconItem_AssetProperties)(nil),                                     // 11: CEconItem_AssetProperties
	(*CEcon_GetInventoryItemsWithDescriptions_Response)(nil),              // 12: CEcon_GetInventoryItemsWithDescriptions_Response
	(*CEcon_GetTradeOfferAccessToken_Request)(nil),                        // 13: CEcon_GetTradeOfferAccessToken_Request
	(*CEcon_GetTradeOfferAccessToken_Response)(nil),                       // 14: CEcon_GetTradeOfferAccessToken_Response
	(*CEcon_ClientGetItemShopOverlayAuthURL_Request)(nil),                 // 15: CEcon_ClientGetItemShopOverlayAuthURL_Request
	(*CEcon_ClientGetItemShopOverlayAuthURL_Response)(nil),                // 16: CEcon_ClientGetItemShopOverlayAuthURL_Response
	(*CEcon_GetAssetClassInfo_Request)(nil),                               // 17: CEcon_GetAssetClassInfo_Request
	(*CEcon_GetAssetClassInfo_Response)(nil),                              // 18: CEcon_GetAssetClassInfo_Response
	(*CEcon_GetAssetPropertySchema_Request)(nil),                          // 19: CEcon_GetAssetPropertySchema_Request
	(*CEconItem_AssetPropertySchema)(nil),                                 // 20: CEconItem_AssetPropertySchema
	(*CEcon_GetAssetPropertySchema_Response)(nil),                         // 21: CEcon_GetAssetPropertySchema_Response
	(*CEcon_GetInventoryItemsWithDescriptions_Request_FilterOptions)(nil), // 22: CEcon_GetInventoryItemsWithDescriptions_Request.FilterOptions
}
var file_steammessages_econ_steamclient_proto_depIdxs = []int32{
	22, // 0: CEcon_GetInventoryItemsWithDescriptions_Request.filters:type_name -> CEcon_GetInventoryItemsWithDescriptions_Request.FilterOptions
	3,  // 1: CEconItem_Description.descriptions:type_name -> CEconItem_DescriptionLine
	4,  // 2: CEconItem_Description.actions:type_name -> CEconItem_Action
	3,  // 3: CEconItem_Description.owner_descriptions:type_name -> CEconItem_DescriptionLine
	4,  // 4: CEconItem_Description.owner_actions:type_name -> CEconItem_Action
	5,  // 5: CEconItem_Description.contained_item:type_name -> CEconItem_Description
	4,  // 6: CEconItem_Description.market_actions:type_name -> CEconItem_Action
	6,  // 7: CEconItem_Description.tags:type_name -> CEconItem_Tag
	8,  // 8: CEconItem_Description.container_properties:type_name -> CEconItem_ContainerProperties
	7,  // 9: CEconItem_ContainerProperties.contained_items:type_name -> CEconItem_ClassIdentifiers
	6,  // 10: CEconItem_ContainerProperties.search_tags:type_name -> CEconItem_Tag
	9,  // 11: CEconItem_AssetAccessory.standalone_properties:type_name -> CEconItem_AssetProperty
	9,  // 12: CEconItem_AssetAccessory.parent_relationship_properties:type_name -> CEconItem_AssetProperty
	10, // 13: CEconItem_AssetAccessory.nested_accessories:type_name -> CEconItem_AssetAccessory
	9,  // 14: CEconItem_AssetProperties.asset_properties:type_name -> CEconItem_AssetProperty
	10, // 15: CEconItem_AssetProperties.asset_accessories:type_name -> CEconItem_AssetAccessory
	2,  // 16: CEcon_GetInventoryItemsWithDescriptions_Response.assets:type_name -> CEcon_Asset
	5,  // 17: CEcon_GetInventoryItemsWithDescriptions_Response.descriptions:type_name -> CEconItem_Description
	2,  // 18: CEcon_GetInventoryItemsWithDescriptions_Response.missing_assets:type_name -> CEcon_Asset
	11, // 19: CEcon_GetInventoryItemsWithDescriptions_Response.asset_properties:type_name -> CEconItem_AssetProperties
	7,  // 20: CEcon_GetAssetClassInfo_Request.classes:type_name -> CEconItem_ClassIdentifiers
	5,  // 21: CEcon_GetAssetClassInfo_Response.descriptions:type_name -> CEconItem_Description
	0,  // 22: CEconItem_AssetPropertySchema.type:type_name -> EAssetPropertyType
	20, // 23: CEcon_GetAssetPropertySchema_Response.property_schemas:type_name -> CEconItem_AssetPropertySchema
	1,  // 24: Econ.GetInventoryItemsWithDescriptions:input_type -> CEcon_GetInventoryItemsWithDescriptions_Request
	13, // 25: Econ.GetTradeOfferAccessToken:input_type -> CEcon_GetTradeOfferAccessToken_Request
	15, // 26: Econ.ClientGetItemShopOverlayAuthURL:input_type -> CEcon_ClientGetItemShopOverlayAuthURL_Request
	17, // 27: Econ.GetAssetClassInfo:input_type -> CEcon_GetAssetClassInfo_Request
	19, // 28: Econ.GetAssetPropertySchema:input_type -> CEcon_GetAssetPropertySchema_Request
	12, // 29: Econ.GetInventoryItemsWithDescriptions:output_type -> CEcon_GetInventoryItemsWithDescriptions_Response
	14, // 30: Econ.GetTradeOfferAccessToken:output_type -> CEcon_GetTradeOfferAccessToken_Response
	16, // 31: Econ.ClientGetItemShopOverlayAuthURL:output_type -> CEcon_ClientGetItemShopOverlayAuthURL_Response
	18, // 32: Econ.GetAssetClassInfo:output_type -> CEcon_GetAssetClassInfo_Response
	21, // 33: Econ.GetAssetPropertySchema:output_type -> CEcon_GetAssetPropertySchema_Response
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_steammessages_econ_steamclient_proto_init() }
func file_steammessages_econ_steamclient_proto_init() {
	if File_steammessages_econ_steamclient_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	file_steammessages_unified_base_steamclient_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steammessages_econ_steamclient_proto_rawDesc), len(file_steammessages_econ_steamclient_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steammessages_econ_steamclient_proto_goTypes,
		DependencyIndexes: file_steammessages_econ_steamclient_proto_depIdxs,
		EnumInfos:         file_steammessages_econ_steamclient_proto_enumTypes,
		MessageInfos:      file_steammessages_econ_steamclient_proto_msgTypes,
	}.Build()
	File_steammessages_econ_steamclient_proto = out.File
	file_steammessages_econ_steamclient_proto_goTypes = nil
	file_steammessages_econ_steamclient_proto_depIdxs = nil
}
