// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: webuimessages_sleep.proto

package steamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ESystemPowerState int32

const (
	ESystemPowerState_k_ESystemPowerState_Invalid           ESystemPowerState = 0
	ESystemPowerState_k_ESystemPowerState_Normal            ESystemPowerState = 1
	ESystemPowerState_k_ESystemPowerState_LowPowerDownloads ESystemPowerState = 2
	ESystemPowerState_k_ESystemPowerState_Sleep             ESystemPowerState = 3
)

// Enum value maps for ESystemPowerState.
var (
	ESystemPowerState_name = map[int32]string{
		0: "k_ESystemPowerState_Invalid",
		1: "k_ESystemPowerState_Normal",
		2: "k_ESystemPowerState_LowPowerDownloads",
		3: "k_ESystemPowerState_Sleep",
	}
	ESystemPowerState_value = map[string]int32{
		"k_ESystemPowerState_Invalid":           0,
		"k_ESystemPowerState_Normal":            1,
		"k_ESystemPowerState_LowPowerDownloads": 2,
		"k_ESystemPowerState_Sleep":             3,
	}
)

func (x ESystemPowerState) Enum() *ESystemPowerState {
	p := new(ESystemPowerState)
	*p = x
	return p
}

func (x ESystemPowerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESystemPowerState) Descriptor() protoreflect.EnumDescriptor {
	return file_webuimessages_sleep_proto_enumTypes[0].Descriptor()
}

func (ESystemPowerState) Type() protoreflect.EnumType {
	return &file_webuimessages_sleep_proto_enumTypes[0]
}

func (x ESystemPowerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ESystemPowerState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ESystemPowerState(num)
	return nil
}

// Deprecated: Use ESystemPowerState.Descriptor instead.
func (ESystemPowerState) EnumDescriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{0}
}

type CMsgSleepManagerState struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	IsLowPowerDownloadSupported *bool                  `protobuf:"varint,1,opt,name=is_low_power_download_supported,json=isLowPowerDownloadSupported" json:"is_low_power_download_supported,omitempty"`
	CurrentState                *ESystemPowerState     `protobuf:"varint,2,opt,name=current_state,json=currentState,enum=ESystemPowerState,def=0" json:"current_state,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

// Default values for CMsgSleepManagerState fields.
const (
	Default_CMsgSleepManagerState_CurrentState = ESystemPowerState_k_ESystemPowerState_Invalid
)

func (x *CMsgSleepManagerState) Reset() {
	*x = CMsgSleepManagerState{}
	mi := &file_webuimessages_sleep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgSleepManagerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgSleepManagerState) ProtoMessage() {}

func (x *CMsgSleepManagerState) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgSleepManagerState.ProtoReflect.Descriptor instead.
func (*CMsgSleepManagerState) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgSleepManagerState) GetIsLowPowerDownloadSupported() bool {
	if x != nil && x.IsLowPowerDownloadSupported != nil {
		return *x.IsLowPowerDownloadSupported
	}
	return false
}

func (x *CMsgSleepManagerState) GetCurrentState() ESystemPowerState {
	if x != nil && x.CurrentState != nil {
		return *x.CurrentState
	}
	return Default_CMsgSleepManagerState_CurrentState
}

type CSleepManager_GetState_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSleepManager_GetState_Request) Reset() {
	*x = CSleepManager_GetState_Request{}
	mi := &file_webuimessages_sleep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_GetState_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_GetState_Request) ProtoMessage() {}

func (x *CSleepManager_GetState_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_GetState_Request.ProtoReflect.Descriptor instead.
func (*CSleepManager_GetState_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{1}
}

type CSleepManager_GetState_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *CMsgSleepManagerState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSleepManager_GetState_Response) Reset() {
	*x = CSleepManager_GetState_Response{}
	mi := &file_webuimessages_sleep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_GetState_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_GetState_Response) ProtoMessage() {}

func (x *CSleepManager_GetState_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_GetState_Response.ProtoReflect.Descriptor instead.
func (*CSleepManager_GetState_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{2}
}

func (x *CSleepManager_GetState_Response) GetState() *CMsgSleepManagerState {
	if x != nil {
		return x.State
	}
	return nil
}

type CSleepManager_StateChanged_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSleepManager_StateChanged_Notification) Reset() {
	*x = CSleepManager_StateChanged_Notification{}
	mi := &file_webuimessages_sleep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_StateChanged_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_StateChanged_Notification) ProtoMessage() {}

func (x *CSleepManager_StateChanged_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_StateChanged_Notification.ProtoReflect.Descriptor instead.
func (*CSleepManager_StateChanged_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{3}
}

type CSleepManager_RequestSuspend_Notification struct {
	state                                   protoimpl.MessageState `protogen:"open.v1"`
	OptionallyTransitionToLowPowerDownloads *bool                  `protobuf:"varint,1,opt,name=optionally_transition_to_low_power_downloads,json=optionallyTransitionToLowPowerDownloads" json:"optionally_transition_to_low_power_downloads,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *CSleepManager_RequestSuspend_Notification) Reset() {
	*x = CSleepManager_RequestSuspend_Notification{}
	mi := &file_webuimessages_sleep_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_RequestSuspend_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_RequestSuspend_Notification) ProtoMessage() {}

func (x *CSleepManager_RequestSuspend_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_RequestSuspend_Notification.ProtoReflect.Descriptor instead.
func (*CSleepManager_RequestSuspend_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{4}
}

func (x *CSleepManager_RequestSuspend_Notification) GetOptionallyTransitionToLowPowerDownloads() bool {
	if x != nil && x.OptionallyTransitionToLowPowerDownloads != nil {
		return *x.OptionallyTransitionToLowPowerDownloads
	}
	return false
}

type CSleepManager_ResumeFromSuspend_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSleepManager_ResumeFromSuspend_Notification) Reset() {
	*x = CSleepManager_ResumeFromSuspend_Notification{}
	mi := &file_webuimessages_sleep_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_ResumeFromSuspend_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_ResumeFromSuspend_Notification) ProtoMessage() {}

func (x *CSleepManager_ResumeFromSuspend_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_ResumeFromSuspend_Notification.ProtoReflect.Descriptor instead.
func (*CSleepManager_ResumeFromSuspend_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{5}
}

type CSleepManager_ShowPowerMenu_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSleepManager_ShowPowerMenu_Notification) Reset() {
	*x = CSleepManager_ShowPowerMenu_Notification{}
	mi := &file_webuimessages_sleep_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_ShowPowerMenu_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_ShowPowerMenu_Notification) ProtoMessage() {}

func (x *CSleepManager_ShowPowerMenu_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_ShowPowerMenu_Notification.ProtoReflect.Descriptor instead.
func (*CSleepManager_ShowPowerMenu_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{6}
}

type CSleepManager_SwitchToPowerState_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ESystemPowerState     `protobuf:"varint,1,opt,name=state,enum=ESystemPowerState,def=0" json:"state,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CSleepManager_SwitchToPowerState_Request fields.
const (
	Default_CSleepManager_SwitchToPowerState_Request_State = ESystemPowerState_k_ESystemPowerState_Invalid
)

func (x *CSleepManager_SwitchToPowerState_Request) Reset() {
	*x = CSleepManager_SwitchToPowerState_Request{}
	mi := &file_webuimessages_sleep_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_SwitchToPowerState_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_SwitchToPowerState_Request) ProtoMessage() {}

func (x *CSleepManager_SwitchToPowerState_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_SwitchToPowerState_Request.ProtoReflect.Descriptor instead.
func (*CSleepManager_SwitchToPowerState_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{7}
}

func (x *CSleepManager_SwitchToPowerState_Request) GetState() ESystemPowerState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return Default_CSleepManager_SwitchToPowerState_Request_State
}

func (x *CSleepManager_SwitchToPowerState_Request) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type CSleepManager_SwitchToPowerState_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSleepManager_SwitchToPowerState_Response) Reset() {
	*x = CSleepManager_SwitchToPowerState_Response{}
	mi := &file_webuimessages_sleep_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_SwitchToPowerState_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_SwitchToPowerState_Response) ProtoMessage() {}

func (x *CSleepManager_SwitchToPowerState_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_SwitchToPowerState_Response.ProtoReflect.Descriptor instead.
func (*CSleepManager_SwitchToPowerState_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{8}
}

type CSleepManager_RequestSleep_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSleepManager_RequestSleep_Request) Reset() {
	*x = CSleepManager_RequestSleep_Request{}
	mi := &file_webuimessages_sleep_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_RequestSleep_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_RequestSleep_Request) ProtoMessage() {}

func (x *CSleepManager_RequestSleep_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_RequestSleep_Request.ProtoReflect.Descriptor instead.
func (*CSleepManager_RequestSleep_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{9}
}

type CSleepManager_RequestSleep_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSleepManager_RequestSleep_Response) Reset() {
	*x = CSleepManager_RequestSleep_Response{}
	mi := &file_webuimessages_sleep_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSleepManager_RequestSleep_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSleepManager_RequestSleep_Response) ProtoMessage() {}

func (x *CSleepManager_RequestSleep_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_sleep_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSleepManager_RequestSleep_Response.ProtoReflect.Descriptor instead.
func (*CSleepManager_RequestSleep_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_sleep_proto_rawDescGZIP(), []int{10}
}

var File_webuimessages_sleep_proto protoreflect.FileDescriptor

const file_webuimessages_sleep_proto_rawDesc = "" +
	"\n" +
	"\x19webuimessages_sleep.proto\x1a\venums.proto\x1a\x18steammessages_base.proto\x1a\x18webuimessages_base.proto\"\xb3\x01\n" +
	"\x15CMsgSleepManagerState\x12D\n" +
	"\x1fis_low_power_download_supported\x18\x01 \x01(\bR\x1bisLowPowerDownloadSupported\x12T\n" +
	"\rcurrent_state\x18\x02 \x01(\x0e2\x12.ESystemPowerState:\x1bk_ESystemPowerState_InvalidR\fcurrentState\" \n" +
	"\x1eCSleepManager_GetState_Request\"O\n" +
	"\x1fCSleepManager_GetState_Response\x12,\n" +
	"\x05state\x18\x01 \x01(\v2\x16.CMsgSleepManagerStateR\x05state\")\n" +
	"'CSleepManager_StateChanged_Notification\"\x8a\x01\n" +
	")CSleepManager_RequestSuspend_Notification\x12]\n" +
	",optionally_transition_to_low_power_downloads\x18\x01 \x01(\bR'optionallyTransitionToLowPowerDownloads\".\n" +
	",CSleepManager_ResumeFromSuspend_Notification\"*\n" +
	"(CSleepManager_ShowPowerMenu_Notification\"\x89\x01\n" +
	"(CSleepManager_SwitchToPowerState_Request\x12E\n" +
	"\x05state\x18\x01 \x01(\x0e2\x12.ESystemPowerState:\x1bk_ESystemPowerState_InvalidR\x05state\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"+\n" +
	")CSleepManager_SwitchToPowerState_Response\"$\n" +
	"\"CSleepManager_RequestSleep_Request\"%\n" +
	"#CSleepManager_RequestSleep_Response*\x9e\x01\n" +
	"\x11ESystemPowerState\x12\x1f\n" +
	"\x1bk_ESystemPowerState_Invalid\x10\x00\x12\x1e\n" +
	"\x1ak_ESystemPowerState_Normal\x10\x01\x12)\n" +
	"%k_ESystemPowerState_LowPowerDownloads\x10\x02\x12\x1d\n" +
	"\x19k_ESystemPowerState_Sleep\x10\x032\x83\x05\n" +
	"\fSleepManager\x12M\n" +
	"\bGetState\x12\x1f.CSleepManager_GetState_Request\x1a .CSleepManager_GetState_Response\x12P\n" +
	"\x12NotifyStateChanged\x12(.CSleepManager_StateChanged_Notification\x1a\x10.WebUINoResponse\x12T\n" +
	"\x14NotifyRequestSuspend\x12*.CSleepManager_RequestSuspend_Notification\x1a\x10.WebUINoResponse\x12Z\n" +
	"\x17NotifyResumeFromSuspend\x12-.CSleepManager_ResumeFromSuspend_Notification\x1a\x10.WebUINoResponse\x12R\n" +
	"\x13NotifyShowPowerMenu\x12).CSleepManager_ShowPowerMenu_Notification\x1a\x10.WebUINoResponse\x12k\n" +
	"\x12SwitchToPowerState\x12).CSleepManager_SwitchToPowerState_Request\x1a*.CSleepManager_SwitchToPowerState_Response\x12Y\n" +
	"\fRequestSleep\x12#.CSleepManager_RequestSleep_Request\x1a$.CSleepManager_RequestSleep_Response\x1a\x04\x80\x97\"\x01B\x05H\x01\x80\x01\x01"

var (
	file_webuimessages_sleep_proto_rawDescOnce sync.Once
	file_webuimessages_sleep_proto_rawDescData []byte
)

func file_webuimessages_sleep_proto_rawDescGZIP() []byte {
	file_webuimessages_sleep_proto_rawDescOnce.Do(func() {
		file_webuimessages_sleep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webuimessages_sleep_proto_rawDesc), len(file_webuimessages_sleep_proto_rawDesc)))
	})
	return file_webuimessages_sleep_proto_rawDescData
}

var file_webuimessages_sleep_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_webuimessages_sleep_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_webuimessages_sleep_proto_goTypes = []any{
	(ESystemPowerState)(0),                               // 0: ESystemPowerState
	(*CMsgSleepManagerState)(nil),                        // 1: CMsgSleepManagerState
	(*CSleepManager_GetState_Request)(nil),               // 2: CSleepManager_GetState_Request
	(*CSleepManager_GetState_Response)(nil),              // 3: CSleepManager_GetState_Response
	(*CSleepManager_StateChanged_Notification)(nil),      // 4: CSleepManager_StateChanged_Notification
	(*CSleepManager_RequestSuspend_Notification)(nil),    // 5: CSleepManager_RequestSuspend_Notification
	(*CSleepManager_ResumeFromSuspend_Notification)(nil), // 6: CSleepManager_ResumeFromSuspend_Notification
	(*CSleepManager_ShowPowerMenu_Notification)(nil),     // 7: CSleepManager_ShowPowerMenu_Notification
	(*CSleepManager_SwitchToPowerState_Request)(nil),     // 8: CSleepManager_SwitchToPowerState_Request
	(*CSleepManager_SwitchToPowerState_Response)(nil),    // 9: CSleepManager_SwitchToPowerState_Response
	(*CSleepManager_RequestSleep_Request)(nil),           // 10: CSleepManager_RequestSleep_Request
	(*CSleepManager_RequestSleep_Response)(nil),          // 11: CSleepManager_RequestSleep_Response
	(*WebUINoResponse)(nil),                              // 12: WebUINoResponse
}
var file_webuimessages_sleep_proto_depIdxs = []int32{
	0,  // 0: CMsgSleepManagerState.current_state:type_name -> ESystemPowerState
	1,  // 1: CSleepManager_GetState_Response.state:type_name -> CMsgSleepManagerState
	0,  // 2: CSleepManager_SwitchToPowerState_Request.state:type_name -> ESystemPowerState
	2,  // 3: SleepManager.GetState:input_type -> CSleepManager_GetState_Request
	4,  // 4: SleepManager.NotifyStateChanged:input_type -> CSleepManager_StateChanged_Notification
	5,  // 5: SleepManager.NotifyRequestSuspend:input_type -> CSleepManager_RequestSuspend_Notification
	6,  // 6: SleepManager.NotifyResumeFromSuspend:input_type -> CSleepManager_ResumeFromSuspend_Notification
	7,  // 7: SleepManager.NotifyShowPowerMenu:input_type -> CSleepManager_ShowPowerMenu_Notification
	8,  // 8: SleepManager.SwitchToPowerState:input_type -> CSleepManager_SwitchToPowerState_Request
	10, // 9: SleepManager.RequestSleep:input_type -> CSleepManager_RequestSleep_Request
	3,  // 10: SleepManager.GetState:output_type -> CSleepManager_GetState_Response
	12, // 11: SleepManager.NotifyStateChanged:output_type -> WebUINoResponse
	12, // 12: SleepManager.NotifyRequestSuspend:output_type -> WebUINoResponse
	12, // 13: SleepManager.NotifyResumeFromSuspend:output_type -> WebUINoResponse
	12, // 14: SleepManager.NotifyShowPowerMenu:output_type -> WebUINoResponse
	9,  // 15: SleepManager.SwitchToPowerState:output_type -> CSleepManager_SwitchToPowerState_Response
	11, // 16: SleepManager.RequestSleep:output_type -> CSleepManager_RequestSleep_Response
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_webuimessages_sleep_proto_init() }
func file_webuimessages_sleep_proto_init() {
	if File_webuimessages_sleep_proto != nil {
		return
	}
	file_enums_proto_init()
	file_steammessages_base_proto_init()
	file_webuimessages_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webuimessages_sleep_proto_rawDesc), len(file_webuimessages_sleep_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webuimessages_sleep_proto_goTypes,
		DependencyIndexes: file_webuimessages_sleep_proto_depIdxs,
		EnumInfos:         file_webuimessages_sleep_proto_enumTypes,
		MessageInfos:      file_webuimessages_sleep_proto_msgTypes,
	}.Build()
	File_webuimessages_sleep_proto = out.File
	file_webuimessages_sleep_proto_goTypes = nil
	file_webuimessages_sleep_proto_depIdxs = nil
}
