// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: webuimessages_transportvalidation.proto

package steamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CTransportValidation_AppendToString_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppendStrings []string               `protobuf:"bytes,1,rep,name=append_strings,json=appendStrings" json:"append_strings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_AppendToString_Request) Reset() {
	*x = CTransportValidation_AppendToString_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_AppendToString_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_AppendToString_Request) ProtoMessage() {}

func (x *CTransportValidation_AppendToString_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_AppendToString_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_AppendToString_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{0}
}

func (x *CTransportValidation_AppendToString_Request) GetAppendStrings() []string {
	if x != nil {
		return x.AppendStrings
	}
	return nil
}

type CTransportValidation_AppendToString_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombinedText  *string                `protobuf:"bytes,1,opt,name=combined_text,json=combinedText" json:"combined_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_AppendToString_Response) Reset() {
	*x = CTransportValidation_AppendToString_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_AppendToString_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_AppendToString_Response) ProtoMessage() {}

func (x *CTransportValidation_AppendToString_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_AppendToString_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_AppendToString_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{1}
}

func (x *CTransportValidation_AppendToString_Response) GetCombinedText() string {
	if x != nil && x.CombinedText != nil {
		return *x.CombinedText
	}
	return ""
}

type CTransportValidation_NotifyText_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *string                `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_NotifyText_Notification) Reset() {
	*x = CTransportValidation_NotifyText_Notification{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_NotifyText_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_NotifyText_Notification) ProtoMessage() {}

func (x *CTransportValidation_NotifyText_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_NotifyText_Notification.ProtoReflect.Descriptor instead.
func (*CTransportValidation_NotifyText_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{2}
}

func (x *CTransportValidation_NotifyText_Notification) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type CTransportValidation_NotifyNumber_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        *int32                 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_NotifyNumber_Notification) Reset() {
	*x = CTransportValidation_NotifyNumber_Notification{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_NotifyNumber_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_NotifyNumber_Notification) ProtoMessage() {}

func (x *CTransportValidation_NotifyNumber_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_NotifyNumber_Notification.ProtoReflect.Descriptor instead.
func (*CTransportValidation_NotifyNumber_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{3}
}

func (x *CTransportValidation_NotifyNumber_Notification) GetNumber() int32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

type CTransportValidation_GetLastNotifyNumber_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_GetLastNotifyNumber_Request) Reset() {
	*x = CTransportValidation_GetLastNotifyNumber_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_GetLastNotifyNumber_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_GetLastNotifyNumber_Request) ProtoMessage() {}

func (x *CTransportValidation_GetLastNotifyNumber_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_GetLastNotifyNumber_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_GetLastNotifyNumber_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{4}
}

type CTransportValidation_GetLastNotifyNumber_Response struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LastNotifyNumber *int32                 `protobuf:"varint,1,opt,name=last_notify_number,json=lastNotifyNumber" json:"last_notify_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CTransportValidation_GetLastNotifyNumber_Response) Reset() {
	*x = CTransportValidation_GetLastNotifyNumber_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_GetLastNotifyNumber_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_GetLastNotifyNumber_Response) ProtoMessage() {}

func (x *CTransportValidation_GetLastNotifyNumber_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_GetLastNotifyNumber_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_GetLastNotifyNumber_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{5}
}

func (x *CTransportValidation_GetLastNotifyNumber_Response) GetLastNotifyNumber() int32 {
	if x != nil && x.LastNotifyNumber != nil {
		return *x.LastNotifyNumber
	}
	return 0
}

type CTransportValidation_TriggerSyntheticEvents_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *int32                 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_TriggerSyntheticEvents_Request) Reset() {
	*x = CTransportValidation_TriggerSyntheticEvents_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_TriggerSyntheticEvents_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_TriggerSyntheticEvents_Request) ProtoMessage() {}

func (x *CTransportValidation_TriggerSyntheticEvents_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_TriggerSyntheticEvents_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_TriggerSyntheticEvents_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{6}
}

func (x *CTransportValidation_TriggerSyntheticEvents_Request) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type CTransportValidation_TriggerSyntheticEvents_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_TriggerSyntheticEvents_Response) Reset() {
	*x = CTransportValidation_TriggerSyntheticEvents_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_TriggerSyntheticEvents_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_TriggerSyntheticEvents_Response) ProtoMessage() {}

func (x *CTransportValidation_TriggerSyntheticEvents_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_TriggerSyntheticEvents_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_TriggerSyntheticEvents_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{7}
}

type CTransportValidation_NotifySyntheticEvent_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      *int32                 `protobuf:"varint,1,opt,name=sequence" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_NotifySyntheticEvent_Notification) Reset() {
	*x = CTransportValidation_NotifySyntheticEvent_Notification{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_NotifySyntheticEvent_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_NotifySyntheticEvent_Notification) ProtoMessage() {}

func (x *CTransportValidation_NotifySyntheticEvent_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_NotifySyntheticEvent_Notification.ProtoReflect.Descriptor instead.
func (*CTransportValidation_NotifySyntheticEvent_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{8}
}

func (x *CTransportValidation_NotifySyntheticEvent_Notification) GetSequence() int32 {
	if x != nil && x.Sequence != nil {
		return *x.Sequence
	}
	return 0
}

type CTransportValidation_TriggerDataRequest_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_TriggerDataRequest_Request) Reset() {
	*x = CTransportValidation_TriggerDataRequest_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_TriggerDataRequest_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_TriggerDataRequest_Request) ProtoMessage() {}

func (x *CTransportValidation_TriggerDataRequest_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_TriggerDataRequest_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_TriggerDataRequest_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{9}
}

type CTransportValidation_TriggerDataRequest_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *int32                 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_TriggerDataRequest_Response) Reset() {
	*x = CTransportValidation_TriggerDataRequest_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_TriggerDataRequest_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_TriggerDataRequest_Response) ProtoMessage() {}

func (x *CTransportValidation_TriggerDataRequest_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_TriggerDataRequest_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_TriggerDataRequest_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{10}
}

func (x *CTransportValidation_TriggerDataRequest_Response) GetData() int32 {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return 0
}

type CTransportValidation_DataRequest_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_DataRequest_Request) Reset() {
	*x = CTransportValidation_DataRequest_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_DataRequest_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_DataRequest_Request) ProtoMessage() {}

func (x *CTransportValidation_DataRequest_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_DataRequest_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_DataRequest_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{11}
}

type CTransportValidation_DataRequest_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *int32                 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_DataRequest_Response) Reset() {
	*x = CTransportValidation_DataRequest_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_DataRequest_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_DataRequest_Response) ProtoMessage() {}

func (x *CTransportValidation_DataRequest_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_DataRequest_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_DataRequest_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{12}
}

func (x *CTransportValidation_DataRequest_Response) GetData() int32 {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return 0
}

type CTransportValidation_AddNumbers_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []int32                `protobuf:"varint,1,rep,name=numbers" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_AddNumbers_Request) Reset() {
	*x = CTransportValidation_AddNumbers_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_AddNumbers_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_AddNumbers_Request) ProtoMessage() {}

func (x *CTransportValidation_AddNumbers_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_AddNumbers_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_AddNumbers_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{13}
}

func (x *CTransportValidation_AddNumbers_Request) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type CTransportValidation_AddNumbers_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accumulated   *int32                 `protobuf:"varint,1,opt,name=accumulated" json:"accumulated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_AddNumbers_Response) Reset() {
	*x = CTransportValidation_AddNumbers_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_AddNumbers_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_AddNumbers_Response) ProtoMessage() {}

func (x *CTransportValidation_AddNumbers_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_AddNumbers_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_AddNumbers_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{14}
}

func (x *CTransportValidation_AddNumbers_Response) GetAccumulated() int32 {
	if x != nil && x.Accumulated != nil {
		return *x.Accumulated
	}
	return 0
}

type CTransportValidation_CountOrderedBytes_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderedBytes  []byte                 `protobuf:"bytes,1,opt,name=ordered_bytes,json=orderedBytes" json:"ordered_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_CountOrderedBytes_Request) Reset() {
	*x = CTransportValidation_CountOrderedBytes_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_CountOrderedBytes_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_CountOrderedBytes_Request) ProtoMessage() {}

func (x *CTransportValidation_CountOrderedBytes_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_CountOrderedBytes_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_CountOrderedBytes_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{15}
}

func (x *CTransportValidation_CountOrderedBytes_Request) GetOrderedBytes() []byte {
	if x != nil {
		return x.OrderedBytes
	}
	return nil
}

type CTransportValidation_CountOrderedBytes_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByteCount     *int32                 `protobuf:"varint,1,opt,name=byte_count,json=byteCount" json:"byte_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_CountOrderedBytes_Response) Reset() {
	*x = CTransportValidation_CountOrderedBytes_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_CountOrderedBytes_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_CountOrderedBytes_Response) ProtoMessage() {}

func (x *CTransportValidation_CountOrderedBytes_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_CountOrderedBytes_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_CountOrderedBytes_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{16}
}

func (x *CTransportValidation_CountOrderedBytes_Response) GetByteCount() int32 {
	if x != nil && x.ByteCount != nil {
		return *x.ByteCount
	}
	return 0
}

type CTransportValidation_ThreadedCount_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartNum      *int32                 `protobuf:"varint,1,opt,name=start_num,json=startNum" json:"start_num,omitempty"`
	EndNum        *int32                 `protobuf:"varint,2,opt,name=end_num,json=endNum" json:"end_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_ThreadedCount_Request) Reset() {
	*x = CTransportValidation_ThreadedCount_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_ThreadedCount_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_ThreadedCount_Request) ProtoMessage() {}

func (x *CTransportValidation_ThreadedCount_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_ThreadedCount_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_ThreadedCount_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{17}
}

func (x *CTransportValidation_ThreadedCount_Request) GetStartNum() int32 {
	if x != nil && x.StartNum != nil {
		return *x.StartNum
	}
	return 0
}

func (x *CTransportValidation_ThreadedCount_Request) GetEndNum() int32 {
	if x != nil && x.EndNum != nil {
		return *x.EndNum
	}
	return 0
}

type CTransportValidation_ThreadedCount_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_ThreadedCount_Response) Reset() {
	*x = CTransportValidation_ThreadedCount_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_ThreadedCount_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_ThreadedCount_Response) ProtoMessage() {}

func (x *CTransportValidation_ThreadedCount_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_ThreadedCount_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_ThreadedCount_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{18}
}

type CTransportValidation_NotifyCount_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           *int32                 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_NotifyCount_Notification) Reset() {
	*x = CTransportValidation_NotifyCount_Notification{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_NotifyCount_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_NotifyCount_Notification) ProtoMessage() {}

func (x *CTransportValidation_NotifyCount_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_NotifyCount_Notification.ProtoReflect.Descriptor instead.
func (*CTransportValidation_NotifyCount_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{19}
}

func (x *CTransportValidation_NotifyCount_Notification) GetNum() int32 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

type CTransportValidation_RequestInvalidBool_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_RequestInvalidBool_Request) Reset() {
	*x = CTransportValidation_RequestInvalidBool_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_RequestInvalidBool_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_RequestInvalidBool_Request) ProtoMessage() {}

func (x *CTransportValidation_RequestInvalidBool_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_RequestInvalidBool_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_RequestInvalidBool_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{20}
}

type CTransportValidation_RequestInvalidBool_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *int32                 `protobuf:"varint,1,opt,name=before" json:"before,omitempty"`
	Output        *bool                  `protobuf:"varint,2,opt,name=output" json:"output,omitempty"`
	After         *int32                 `protobuf:"varint,3,opt,name=after" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_RequestInvalidBool_Response) Reset() {
	*x = CTransportValidation_RequestInvalidBool_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_RequestInvalidBool_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_RequestInvalidBool_Response) ProtoMessage() {}

func (x *CTransportValidation_RequestInvalidBool_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_RequestInvalidBool_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_RequestInvalidBool_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{21}
}

func (x *CTransportValidation_RequestInvalidBool_Response) GetBefore() int32 {
	if x != nil && x.Before != nil {
		return *x.Before
	}
	return 0
}

func (x *CTransportValidation_RequestInvalidBool_Response) GetOutput() bool {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return false
}

func (x *CTransportValidation_RequestInvalidBool_Response) GetAfter() int32 {
	if x != nil && x.After != nil {
		return *x.After
	}
	return 0
}

type CTransportValidation_GetLargeResponse_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataSize      *uint32                `protobuf:"varint,1,opt,name=data_size,json=dataSize" json:"data_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_GetLargeResponse_Request) Reset() {
	*x = CTransportValidation_GetLargeResponse_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_GetLargeResponse_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_GetLargeResponse_Request) ProtoMessage() {}

func (x *CTransportValidation_GetLargeResponse_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_GetLargeResponse_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_GetLargeResponse_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{22}
}

func (x *CTransportValidation_GetLargeResponse_Request) GetDataSize() uint32 {
	if x != nil && x.DataSize != nil {
		return *x.DataSize
	}
	return 0
}

type CTransportValidation_GetLargeResponse_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_GetLargeResponse_Response) Reset() {
	*x = CTransportValidation_GetLargeResponse_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_GetLargeResponse_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_GetLargeResponse_Response) ProtoMessage() {}

func (x *CTransportValidation_GetLargeResponse_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_GetLargeResponse_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_GetLargeResponse_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{23}
}

func (x *CTransportValidation_GetLargeResponse_Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CTransportValidation_RequestLargeNotification_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataSize      *uint32                `protobuf:"varint,1,opt,name=data_size,json=dataSize" json:"data_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_RequestLargeNotification_Request) Reset() {
	*x = CTransportValidation_RequestLargeNotification_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_RequestLargeNotification_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_RequestLargeNotification_Request) ProtoMessage() {}

func (x *CTransportValidation_RequestLargeNotification_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_RequestLargeNotification_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidation_RequestLargeNotification_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{24}
}

func (x *CTransportValidation_RequestLargeNotification_Request) GetDataSize() uint32 {
	if x != nil && x.DataSize != nil {
		return *x.DataSize
	}
	return 0
}

type CTransportValidation_RequestLargeNotification_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_RequestLargeNotification_Response) Reset() {
	*x = CTransportValidation_RequestLargeNotification_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_RequestLargeNotification_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_RequestLargeNotification_Response) ProtoMessage() {}

func (x *CTransportValidation_RequestLargeNotification_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_RequestLargeNotification_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidation_RequestLargeNotification_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{25}
}

type CTransportValidation_NotifyLarge_Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidation_NotifyLarge_Notification) Reset() {
	*x = CTransportValidation_NotifyLarge_Notification{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidation_NotifyLarge_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidation_NotifyLarge_Notification) ProtoMessage() {}

func (x *CTransportValidation_NotifyLarge_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidation_NotifyLarge_Notification.ProtoReflect.Descriptor instead.
func (*CTransportValidation_NotifyLarge_Notification) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{26}
}

func (x *CTransportValidation_NotifyLarge_Notification) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CTransportValidationClient_AddNumbers_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []int32                `protobuf:"varint,1,rep,name=numbers" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidationClient_AddNumbers_Request) Reset() {
	*x = CTransportValidationClient_AddNumbers_Request{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidationClient_AddNumbers_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidationClient_AddNumbers_Request) ProtoMessage() {}

func (x *CTransportValidationClient_AddNumbers_Request) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidationClient_AddNumbers_Request.ProtoReflect.Descriptor instead.
func (*CTransportValidationClient_AddNumbers_Request) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{27}
}

func (x *CTransportValidationClient_AddNumbers_Request) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type CTransportValidationClient_AddNumbers_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accumulated   *int32                 `protobuf:"varint,1,opt,name=accumulated" json:"accumulated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTransportValidationClient_AddNumbers_Response) Reset() {
	*x = CTransportValidationClient_AddNumbers_Response{}
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTransportValidationClient_AddNumbers_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportValidationClient_AddNumbers_Response) ProtoMessage() {}

func (x *CTransportValidationClient_AddNumbers_Response) ProtoReflect() protoreflect.Message {
	mi := &file_webuimessages_transportvalidation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportValidationClient_AddNumbers_Response.ProtoReflect.Descriptor instead.
func (*CTransportValidationClient_AddNumbers_Response) Descriptor() ([]byte, []int) {
	return file_webuimessages_transportvalidation_proto_rawDescGZIP(), []int{28}
}

func (x *CTransportValidationClient_AddNumbers_Response) GetAccumulated() int32 {
	if x != nil && x.Accumulated != nil {
		return *x.Accumulated
	}
	return 0
}

var File_webuimessages_transportvalidation_proto protoreflect.FileDescriptor

const file_webuimessages_transportvalidation_proto_rawDesc = "" +
	"\n" +
	"'webuimessages_transportvalidation.proto\x1a\x18steammessages_base.proto\x1a\x18webuimessages_base.proto\"T\n" +
	"+CTransportValidation_AppendToString_Request\x12%\n" +
	"\x0eappend_strings\x18\x01 \x03(\tR\rappendStrings\"S\n" +
	",CTransportValidation_AppendToString_Response\x12#\n" +
	"\rcombined_text\x18\x01 \x01(\tR\fcombinedText\"B\n" +
	",CTransportValidation_NotifyText_Notification\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"H\n" +
	".CTransportValidation_NotifyNumber_Notification\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\"2\n" +
	"0CTransportValidation_GetLastNotifyNumber_Request\"a\n" +
	"1CTransportValidation_GetLastNotifyNumber_Response\x12,\n" +
	"\x12last_notify_number\x18\x01 \x01(\x05R\x10lastNotifyNumber\"K\n" +
	"3CTransportValidation_TriggerSyntheticEvents_Request\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"6\n" +
	"4CTransportValidation_TriggerSyntheticEvents_Response\"T\n" +
	"6CTransportValidation_NotifySyntheticEvent_Notification\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\"1\n" +
	"/CTransportValidation_TriggerDataRequest_Request\"F\n" +
	"0CTransportValidation_TriggerDataRequest_Response\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x05R\x04data\"*\n" +
	"(CTransportValidation_DataRequest_Request\"?\n" +
	")CTransportValidation_DataRequest_Response\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x05R\x04data\"C\n" +
	"'CTransportValidation_AddNumbers_Request\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x05R\anumbers\"L\n" +
	"(CTransportValidation_AddNumbers_Response\x12 \n" +
	"\vaccumulated\x18\x01 \x01(\x05R\vaccumulated\"U\n" +
	".CTransportValidation_CountOrderedBytes_Request\x12#\n" +
	"\rordered_bytes\x18\x01 \x01(\fR\forderedBytes\"P\n" +
	"/CTransportValidation_CountOrderedBytes_Response\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x01 \x01(\x05R\tbyteCount\"b\n" +
	"*CTransportValidation_ThreadedCount_Request\x12\x1b\n" +
	"\tstart_num\x18\x01 \x01(\x05R\bstartNum\x12\x17\n" +
	"\aend_num\x18\x02 \x01(\x05R\x06endNum\"-\n" +
	"+CTransportValidation_ThreadedCount_Response\"A\n" +
	"-CTransportValidation_NotifyCount_Notification\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\"1\n" +
	"/CTransportValidation_RequestInvalidBool_Request\"x\n" +
	"0CTransportValidation_RequestInvalidBool_Response\x12\x16\n" +
	"\x06before\x18\x01 \x01(\x05R\x06before\x12\x16\n" +
	"\x06output\x18\x02 \x01(\bR\x06output\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x05R\x05after\"L\n" +
	"-CTransportValidation_GetLargeResponse_Request\x12\x1b\n" +
	"\tdata_size\x18\x01 \x01(\rR\bdataSize\"D\n" +
	".CTransportValidation_GetLargeResponse_Response\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"T\n" +
	"5CTransportValidation_RequestLargeNotification_Request\x12\x1b\n" +
	"\tdata_size\x18\x01 \x01(\rR\bdataSize\"8\n" +
	"6CTransportValidation_RequestLargeNotification_Response\"C\n" +
	"-CTransportValidation_NotifyLarge_Notification\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"I\n" +
	"-CTransportValidationClient_AddNumbers_Request\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x05R\anumbers\"R\n" +
	".CTransportValidationClient_AddNumbers_Response\x12 \n" +
	"\vaccumulated\x18\x01 \x01(\x05R\vaccumulated2\xe5\f\n" +
	"\x13TransportValidation\x12m\n" +
	"\x0eAppendToString\x12,.CTransportValidation_AppendToString_Request\x1a-.CTransportValidation_AppendToString_Response\x12a\n" +
	"\n" +
	"AddNumbers\x12(.CTransportValidation_AddNumbers_Request\x1a).CTransportValidation_AddNumbers_Response\x12g\n" +
	"\x10AddNumbersStatic\x12(.CTransportValidation_AddNumbers_Request\x1a).CTransportValidation_AddNumbers_Response\x12M\n" +
	"\n" +
	"NotifyText\x12-.CTransportValidation_NotifyText_Notification\x1a\x10.WebUINoResponse\x12Q\n" +
	"\fNotifyNumber\x12/.CTransportValidation_NotifyNumber_Notification\x1a\x10.WebUINoResponse\x12|\n" +
	"\x13GetLastNotifyNumber\x121.CTransportValidation_GetLastNotifyNumber_Request\x1a2.CTransportValidation_GetLastNotifyNumber_Response\x12a\n" +
	"\x14NotifySyntheticEvent\x127.CTransportValidation_NotifySyntheticEvent_Notification\x1a\x10.WebUINoResponse\x12\x85\x01\n" +
	"\x16TriggerSyntheticEvents\x124.CTransportValidation_TriggerSyntheticEvents_Request\x1a5.CTransportValidation_TriggerSyntheticEvents_Response\x12v\n" +
	"\x11CountOrderedBytes\x12/.CTransportValidation_CountOrderedBytes_Request\x1a0.CTransportValidation_CountOrderedBytes_Response\x12j\n" +
	"\rThreadedCount\x12+.CTransportValidation_ThreadedCount_Request\x1a,.CTransportValidation_ThreadedCount_Response\x12O\n" +
	"\vNotifyCount\x12..CTransportValidation_NotifyCount_Notification\x1a\x10.WebUINoResponse\x12y\n" +
	"\x12RequestInvalidBool\x120.CTransportValidation_RequestInvalidBool_Request\x1a1.CTransportValidation_RequestInvalidBool_Response\x12s\n" +
	"\x10GetLargeResponse\x12..CTransportValidation_GetLargeResponse_Request\x1a/.CTransportValidation_GetLargeResponse_Response\x12\x8b\x01\n" +
	"\x18RequestLargeNotification\x126.CTransportValidation_RequestLargeNotification_Request\x1a7.CTransportValidation_RequestLargeNotification_Response\x12O\n" +
	"\vNotifyLarge\x12..CTransportValidation_NotifyLarge_Notification\x1a\x10.WebUINoResponse\x1a\x04\x80\x97\"\x012\x90\x01\n" +
	"\x19TransportValidationClient\x12m\n" +
	"\n" +
	"AddNumbers\x12..CTransportValidationClient_AddNumbers_Request\x1a/.CTransportValidationClient_AddNumbers_Response\x1a\x04\x80\x97\"\x02B\x05H\x01\x80\x01\x01"

var (
	file_webuimessages_transportvalidation_proto_rawDescOnce sync.Once
	file_webuimessages_transportvalidation_proto_rawDescData []byte
)

func file_webuimessages_transportvalidation_proto_rawDescGZIP() []byte {
	file_webuimessages_transportvalidation_proto_rawDescOnce.Do(func() {
		file_webuimessages_transportvalidation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webuimessages_transportvalidation_proto_rawDesc), len(file_webuimessages_transportvalidation_proto_rawDesc)))
	})
	return file_webuimessages_transportvalidation_proto_rawDescData
}

var file_webuimessages_transportvalidation_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_webuimessages_transportvalidation_proto_goTypes = []any{
	(*CTransportValidation_AppendToString_Request)(nil),            // 0: CTransportValidation_AppendToString_Request
	(*CTransportValidation_AppendToString_Response)(nil),           // 1: CTransportValidation_AppendToString_Response
	(*CTransportValidation_NotifyText_Notification)(nil),           // 2: CTransportValidation_NotifyText_Notification
	(*CTransportValidation_NotifyNumber_Notification)(nil),         // 3: CTransportValidation_NotifyNumber_Notification
	(*CTransportValidation_GetLastNotifyNumber_Request)(nil),       // 4: CTransportValidation_GetLastNotifyNumber_Request
	(*CTransportValidation_GetLastNotifyNumber_Response)(nil),      // 5: CTransportValidation_GetLastNotifyNumber_Response
	(*CTransportValidation_TriggerSyntheticEvents_Request)(nil),    // 6: CTransportValidation_TriggerSyntheticEvents_Request
	(*CTransportValidation_TriggerSyntheticEvents_Response)(nil),   // 7: CTransportValidation_TriggerSyntheticEvents_Response
	(*CTransportValidation_NotifySyntheticEvent_Notification)(nil), // 8: CTransportValidation_NotifySyntheticEvent_Notification
	(*CTransportValidation_TriggerDataRequest_Request)(nil),        // 9: CTransportValidation_TriggerDataRequest_Request
	(*CTransportValidation_TriggerDataRequest_Response)(nil),       // 10: CTransportValidation_TriggerDataRequest_Response
	(*CTransportValidation_DataRequest_Request)(nil),               // 11: CTransportValidation_DataRequest_Request
	(*CTransportValidation_DataRequest_Response)(nil),              // 12: CTransportValidation_DataRequest_Response
	(*CTransportValidation_AddNumbers_Request)(nil),                // 13: CTransportValidation_AddNumbers_Request
	(*CTransportValidation_AddNumbers_Response)(nil),               // 14: CTransportValidation_AddNumbers_Response
	(*CTransportValidation_CountOrderedBytes_Request)(nil),         // 15: CTransportValidation_CountOrderedBytes_Request
	(*CTransportValidation_CountOrderedBytes_Response)(nil),        // 16: CTransportValidation_CountOrderedBytes_Response
	(*CTransportValidation_ThreadedCount_Request)(nil),             // 17: CTransportValidation_ThreadedCount_Request
	(*CTransportValidation_ThreadedCount_Response)(nil),            // 18: CTransportValidation_ThreadedCount_Response
	(*CTransportValidation_NotifyCount_Notification)(nil),          // 19: CTransportValidation_NotifyCount_Notification
	(*CTransportValidation_RequestInvalidBool_Request)(nil),        // 20: CTransportValidation_RequestInvalidBool_Request
	(*CTransportValidation_RequestInvalidBool_Response)(nil),       // 21: CTransportValidation_RequestInvalidBool_Response
	(*CTransportValidation_GetLargeResponse_Request)(nil),          // 22: CTransportValidation_GetLargeResponse_Request
	(*CTransportValidation_GetLargeResponse_Response)(nil),         // 23: CTransportValidation_GetLargeResponse_Response
	(*CTransportValidation_RequestLargeNotification_Request)(nil),  // 24: CTransportValidation_RequestLargeNotification_Request
	(*CTransportValidation_RequestLargeNotification_Response)(nil), // 25: CTransportValidation_RequestLargeNotification_Response
	(*CTransportValidation_NotifyLarge_Notification)(nil),          // 26: CTransportValidation_NotifyLarge_Notification
	(*CTransportValidationClient_AddNumbers_Request)(nil),          // 27: CTransportValidationClient_AddNumbers_Request
	(*CTransportValidationClient_AddNumbers_Response)(nil),         // 28: CTransportValidationClient_AddNumbers_Response
	(*WebUINoResponse)(nil),                                        // 29: WebUINoResponse
}
var file_webuimessages_transportvalidation_proto_depIdxs = []int32{
	0,  // 0: TransportValidation.AppendToString:input_type -> CTransportValidation_AppendToString_Request
	13, // 1: TransportValidation.AddNumbers:input_type -> CTransportValidation_AddNumbers_Request
	13, // 2: TransportValidation.AddNumbersStatic:input_type -> CTransportValidation_AddNumbers_Request
	2,  // 3: TransportValidation.NotifyText:input_type -> CTransportValidation_NotifyText_Notification
	3,  // 4: TransportValidation.NotifyNumber:input_type -> CTransportValidation_NotifyNumber_Notification
	4,  // 5: TransportValidation.GetLastNotifyNumber:input_type -> CTransportValidation_GetLastNotifyNumber_Request
	8,  // 6: TransportValidation.NotifySyntheticEvent:input_type -> CTransportValidation_NotifySyntheticEvent_Notification
	6,  // 7: TransportValidation.TriggerSyntheticEvents:input_type -> CTransportValidation_TriggerSyntheticEvents_Request
	15, // 8: TransportValidation.CountOrderedBytes:input_type -> CTransportValidation_CountOrderedBytes_Request
	17, // 9: TransportValidation.ThreadedCount:input_type -> CTransportValidation_ThreadedCount_Request
	19, // 10: TransportValidation.NotifyCount:input_type -> CTransportValidation_NotifyCount_Notification
	20, // 11: TransportValidation.RequestInvalidBool:input_type -> CTransportValidation_RequestInvalidBool_Request
	22, // 12: TransportValidation.GetLargeResponse:input_type -> CTransportValidation_GetLargeResponse_Request
	24, // 13: TransportValidation.RequestLargeNotification:input_type -> CTransportValidation_RequestLargeNotification_Request
	26, // 14: TransportValidation.NotifyLarge:input_type -> CTransportValidation_NotifyLarge_Notification
	27, // 15: TransportValidationClient.AddNumbers:input_type -> CTransportValidationClient_AddNumbers_Request
	1,  // 16: TransportValidation.AppendToString:output_type -> CTransportValidation_AppendToString_Response
	14, // 17: TransportValidation.AddNumbers:output_type -> CTransportValidation_AddNumbers_Response
	14, // 18: TransportValidation.AddNumbersStatic:output_type -> CTransportValidation_AddNumbers_Response
	29, // 19: TransportValidation.NotifyText:output_type -> WebUINoResponse
	29, // 20: TransportValidation.NotifyNumber:output_type -> WebUINoResponse
	5,  // 21: TransportValidation.GetLastNotifyNumber:output_type -> CTransportValidation_GetLastNotifyNumber_Response
	29, // 22: TransportValidation.NotifySyntheticEvent:output_type -> WebUINoResponse
	7,  // 23: TransportValidation.TriggerSyntheticEvents:output_type -> CTransportValidation_TriggerSyntheticEvents_Response
	16, // 24: TransportValidation.CountOrderedBytes:output_type -> CTransportValidation_CountOrderedBytes_Response
	18, // 25: TransportValidation.ThreadedCount:output_type -> CTransportValidation_ThreadedCount_Response
	29, // 26: TransportValidation.NotifyCount:output_type -> WebUINoResponse
	21, // 27: TransportValidation.RequestInvalidBool:output_type -> CTransportValidation_RequestInvalidBool_Response
	23, // 28: TransportValidation.GetLargeResponse:output_type -> CTransportValidation_GetLargeResponse_Response
	25, // 29: TransportValidation.RequestLargeNotification:output_type -> CTransportValidation_RequestLargeNotification_Response
	29, // 30: TransportValidation.NotifyLarge:output_type -> WebUINoResponse
	28, // 31: TransportValidationClient.AddNumbers:output_type -> CTransportValidationClient_AddNumbers_Response
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_webuimessages_transportvalidation_proto_init() }
func file_webuimessages_transportvalidation_proto_init() {
	if File_webuimessages_transportvalidation_proto != nil {
		return
	}
	file_steammessages_base_proto_init()
	file_webuimessages_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webuimessages_transportvalidation_proto_rawDesc), len(file_webuimessages_transportvalidation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_webuimessages_transportvalidation_proto_goTypes,
		DependencyIndexes: file_webuimessages_transportvalidation_proto_depIdxs,
		MessageInfos:      file_webuimessages_transportvalidation_proto_msgTypes,
	}.Build()
	File_webuimessages_transportvalidation_proto = out.File
	file_webuimessages_transportvalidation_proto_goTypes = nil
	file_webuimessages_transportvalidation_proto_depIdxs = nil
}
