package vapor

import (
	steamproto "github.com/mewowz/vapor/internal/steamproto"
	"google.golang.org/protobuf/proto"
)

var emsgToCMsg = map[EMsg]func() proto.Message{
	EMsgMulti:                                   func() proto.Message { return &steamproto.CMsgMulti{} },
	EMsgProtobufWrapped:                         func() proto.Message { return &steamproto.CMsgProtobufWrapped{} },
	EMsgClientHeartBeat:                         func() proto.Message { return &steamproto.CMsgClientHeartBeat{} },
	EMsgClientLogOff:                            func() proto.Message { return &steamproto.CMsgClientLogOff{} },
	EMsgClientConnectionStats:                   func() proto.Message { return &steamproto.CMsgClientConnectionStats{} },
	EMsgClientGamesPlayed:                       func() proto.Message { return &steamproto.CMsgClientGamesPlayed{} },
	EMsgClientLoggedOff:                         func() proto.Message { return &steamproto.CMsgClientLoggedOff{} },
	EMsgGSApprove:                               func() proto.Message { return &steamproto.CMsgGSApprove{} },
	EMsgGSDeny:                                  func() proto.Message { return &steamproto.CMsgGSDeny{} },
	EMsgGSKick:                                  func() proto.Message { return &steamproto.CMsgGSKick{} },
	EMsgClientAccountInfo:                       func() proto.Message { return &steamproto.CMsgClientAccountInfo{} },
	EMsgClientGameConnectTokens:                 func() proto.Message { return &steamproto.CMsgClientGameConnectTokens{} },
	EMsgClientLicenseList:                       func() proto.Message { return &steamproto.CMsgClientLicenseList{} },
	EMsgClientChatInvite:                        func() proto.Message { return &steamproto.CMsgClientChatInvite{} },
	EMsgClientClanState:                         func() proto.Message { return &steamproto.CMsgClientClanState{} },
	EMsgClientSessionToken:                      func() proto.Message { return &steamproto.CMsgClientSessionToken{} },
	EMsgClientGetAppOwnershipTicket:             func() proto.Message { return &steamproto.CMsgClientGetAppOwnershipTicket{} },
	EMsgClientGetAppOwnershipTicketResponse:     func() proto.Message { return &steamproto.CMsgClientGetAppOwnershipTicketResponse{} },
	EMsgClientTicketAuthComplete:                func() proto.Message { return &steamproto.CMsgClientTicketAuthComplete{} },
	EMsgClientIsLimitedAccount:                  func() proto.Message { return &steamproto.CMsgClientIsLimitedAccount{} },
	EMsgClientAuthList:                          func() proto.Message { return &steamproto.CMsgClientAuthList{} },
	EMsgClientP2PConnectionInfo:                 func() proto.Message { return &steamproto.CMsgClientP2PConnectionInfo{} },
	EMsgClientP2PConnectionFailInfo:             func() proto.Message { return &steamproto.CMsgClientP2PConnectionFailInfo{} },
	EMsgClientNewLoginKey:                       func() proto.Message { return &steamproto.CMsgClientNewLoginKey{} },
	EMsgClientServersAvailable:                  func() proto.Message { return &steamproto.CMsgClientServersAvailable{} },
	EMsgClientRegisterAuthTicketWithCM:          func() proto.Message { return &steamproto.CMsgClientRegisterAuthTicketWithCM{} },
	EMsgClientDeregisterWithServer:              func() proto.Message { return &steamproto.CMsgClientDeregisterWithServer{} },
	EMsgClientLogon:                             func() proto.Message { return &steamproto.CMsgClientLogon{} },
	EMsgClientLogOnResponse:                     func() proto.Message { return &steamproto.CMsgClientLogonResponse{} },
	EMsgClientReportOverlayDetourFailure:        func() proto.Message { return &steamproto.CMsgClientReportOverlayDetourFailure{} },
	EMsgClientRequestEncryptedAppTicket:         func() proto.Message { return &steamproto.CMsgClientRequestEncryptedAppTicket{} },
	EMsgClientRequestEncryptedAppTicketResponse: func() proto.Message { return &steamproto.CMsgClientRequestEncryptedAppTicketResponse{} },
	EMsgClientWalletInfoUpdate:                  func() proto.Message { return &steamproto.CMsgClientWalletInfoUpdate{} },
	EMsgClientAMGetClanOfficers:                 func() proto.Message { return &steamproto.CMsgClientAMGetClanOfficers{} },
	EMsgClientAMGetClanOfficersResponse:         func() proto.Message { return &steamproto.CMsgClientAMGetClanOfficersResponse{} },
	EMsgClientAMGetPersonaNameHistory:           func() proto.Message { return &steamproto.CMsgClientAMGetPersonaNameHistory{} },
	EMsgClientAMGetPersonaNameHistoryResponse:   func() proto.Message { return &steamproto.CMsgClientAMGetPersonaNameHistoryResponse{} },
	EMsgClientAuthListAck:                       func() proto.Message { return &steamproto.CMsgClientAuthListAck{} },
	EMsgClientNetworkingCertRequest:             func() proto.Message { return &steamproto.CMsgClientNetworkingCertRequest{} },
	EMsgClientChallengeRequest:                  func() proto.Message { return &steamproto.CMsgClientChallengeRequest{} },
	EMsgClientChallengeResponse:                 func() proto.Message { return &steamproto.CMsgClientChallengeResponse{} },
	EMsgClientNetworkingMobileCertRequest:       func() proto.Message { return &steamproto.CMsgClientNetworkingMobileCertRequest{} },
	EMsgGameServerPolicyUpdate:                  func() proto.Message { return &steamproto.CMsgGameServerPolicyUpdate{} },
	EMsgClientInviteToGame:                      func() proto.Message { return &steamproto.CMsgClientInviteToGame{} },
	EMsgClientServerTimestampRequest:            func() proto.Message { return &steamproto.CMsgClientServerTimestampRequest{} },
	EMsgClientServerTimestampResponse:           func() proto.Message { return &steamproto.CMsgClientServerTimestampResponse{} },
	EMsgClientHello:                             func() proto.Message { return &steamproto.CMsgClientHello{} },
}
