REPO := github.com/mewowz/vapor
PROTO_DIR := internal/proto/steam
PROTO_OUT := internal/steamproto
PROTO_FILES := $(wildcard $(PROTO_DIR)/*.proto)

.PHONY: proto
proto:
	mkdir -p $(PROTO_OUT)
	protoc \
		-I $(PROTO_DIR) \
		--go_out=$(PROTO_OUT) \
		--go_opt=paths=source_relative \
		$(foreach f,$(PROTO_FILES),--go_opt=M$(notdir $(f))=$(REPO)/$(PROTO_OUT) ) \
		$(PROTO_FILES)

.PHONY: emsg
emsg: ENUM_FILE = emsg_enums.go
emsg:
	@echo "package vapor" > $(ENUM_FILE)
	@echo -e "\ntype EMsg uint32\n" >> $(ENUM_FILE)
	@echo "const (" >> $(ENUM_FILE)
	@grep -E "^\s+k_EMsg[A-Za-z0-9_]+ = [0-9]+" $(PROTO_DIR)/enums_clientserver.proto | \
		sed -E 's/[[:space:]]*k_EMsg([A-Za-z0-9_]+)[[:space:]]*=[[:space:]]*([0-9]+).*/\tEMsg\1 EMsg = \2/' >> $(ENUM_FILE)
	@echo ")" >> $(ENUM_FILE)
	@gofmt -w $(ENUM_FILE)

.PHONY: emsg-map
emsg-map: proto emsg
emsg-map: MAP_FILE = emsg_map.go
emsg-map:
	@awk -v repo=$(REPO) ' \
		NR==FNR { \
			if ($$0 ~ /^[[:space:]]*k_EMsg[A-Za-z0-9_]+[[:space:]]*=[[:space:]]*[0-9]+/) { \
				line=$$0; \
				sub(/^[[:space:]]*k_EMsg/, "", line); \
				name=line; sub(/[[:space:]]*=.*$$/, "", name); \
				val=line; sub(/^[A-Za-z0-9_]*[[:space:]]*=[[:space:]]*/, "", val); sub(/[^0-9].*/, "", val); \
				if (!(val in seen)) { seen[val]=1; order[++n]=name; emval[name]=val; } \
			} \
			next; \
		} \
		/^message CMsg[A-Za-z0-9_]+/ { \
			line=$$0; sub(/^message CMsg/, "", line); sub(/[[:space:]].*$$/, "", line); \
			lc=tolower(line); \
			if (!(lc in cmsg)) cmsg[lc]=line; \
		} \
		END { \
			print "package vapor"; \
			print ""; \
			print "import ("; \
			print "\t\"google.golang.org/protobuf/proto\""; \
			print "\tsteamproto \"" repo "/internal/steamproto\""; \
			print ")"; \
			print ""; \
			print "// emsgToCMsg maps an EMsg to a constructor for its corresponding CMsg."; \
			print "// Generated by '\''make emsg-map'\''. Do not edit directly; see unmatched entries below."; \
			print "var emsgToCMsg = map[EMsg]func() proto.Message{"; \
			mn=0; un=0; \
			for (i=1;i<=n;i++) { \
				name=order[i]; lc=tolower(name); found=""; \
				if (lc in cmsg) found=cmsg[lc]; \
				else if (("client" lc) in cmsg) found=cmsg["client" lc]; \
				else if (substr(lc,1,6)=="client" && (substr(lc,7) in cmsg)) found=cmsg[substr(lc,7)]; \
				if (found != "") matched[++mn] = "\tEMsg" name ": func() proto.Message { return &steamproto.CMsg" found "{} },"; \
				else unmatched[++un] = "// " name " = " emval[name]; \
			} \
			for (i=1;i<=mn;i++) print matched[i]; \
			print "}"; \
			print ""; \
			print "// Unmatched EMsgs (no message named CMsg<Name> exists in the proto sources above;"; \
			print "// add an override entry to the map if the real type is named something else):"; \
			for (i=1;i<=un;i++) print unmatched[i]; \
		} \
	' internal/proto/steam/enums_clientserver.proto $(PROTO_FILES) > $(MAP_FILE)
	@gofmt -w $(MAP_FILE)
